"""sources.yaml diff/render/apply — extracted from audit_source.py (Phase 141)."""


import logging
import shutil
from pathlib import Path
from typing import Any, Optional
from urllib.parse import urlparse


from audit_pattern import (infer_safe_pattern)

logger = logging.getLogger(__name__)

def _format_yaml_suggestion(report: dict[str, Any]) -> str:
    """Render the report as a `discovery:` block ready for sources.yaml."""
    lines = ["# Suggested sources.yaml `discovery:` block — review before committing."]
    lines.append("# Generated by `audit_source.py` (Phase 122g).")
    lines.append("#")
    lines.append(f"# Audited: {report['homepage']}")
    lines.append("#")
    lines.append("discovery:")

    sm = report.get("trafilatura_sitemaps_found")
    if isinstance(sm, list) and sm:
        lines.append("  sitemap_urls:")
        for url in sm[:8]:
            lines.append(f"    - {url}")
        if len(sm) > 8:
            lines.append(f"    # ... and {len(sm) - 8} more reported by trafilatura.sitemaps.sitemap_search")
    else:
        lines.append("  sitemap_urls: []   # none surfaced by auto-discovery")

    # Trafilatura's `find_feed_urls` returns *article* URLs from the
    # discovered feeds, not feed URLs themselves. We can't directly
    # populate `rss_hint_urls` from it. Operator must visit the
    # publisher's RSS catalogue page manually.
    feeds = report.get("trafilatura_feeds_found")
    if isinstance(feeds, list) and feeds:
        lines.append("  rss_hint_urls:")
        lines.append("    # IMPORTANT: trafilatura returns article URLs, not feed URLs.")
        lines.append("    # Visit the publisher's RSS / newsletter page and enumerate")
        lines.append("    # the actual feed URLs. Many publishers (e.g. bundesregierung)")
        lines.append("    # publish a feed catalogue at /service/newsletter-und-abos or similar.")
        lines.append(f"    # trafilatura surfaced {len(feeds)} article URL(s) from its feed walk.")
        lines.append("    # - https://example.com/rss/feed.xml")
    else:
        lines.append("  rss_hint_urls: []  # operator: enumerate feeds from publisher catalogue page")

    html_hits = report.get("html_sitemap_candidates") or []
    if html_hits:
        lines.append("  html_sitemap_urls:")
        for hit in html_hits:
            if hit.get("skipped"):
                continue
            lines.append(f"    - url: {hit['url']}")
            lines.append("      article_url_pattern: '<edit-me — regex matching article URLs only>'")
    else:
        lines.append("  html_sitemap_urls: []  # no publisher-built HTML sitemap found at common paths")

    archive_hits = report.get("archive_index_candidates") or []
    if archive_hits:
        lines.append("  archive_index:")
        for hit in archive_hits:
            if hit.get("skipped"):
                continue
            lines.append(f"    url_template: {hit['url_template']}")
            lines.append("    date_format: \"%Y-%m-%d\"")
            lines.append("    granularity: daily   # operator: verify daily vs monthly by sampling two dates")
            lines.append("    article_url_pattern: '<edit-me — regex matching article URLs only>'")
            break  # one block; operator picks one if multiple matched
    else:
        lines.append("  # archive_index: not detected at common paths")

    # Phase 148d (WP-007 §6) — a MEASURED floor seed: half the inventory the
    # audit observed across channels, so the underflow alert is sane from run
    # one. The runtime `declared` telemetry is the authoritative signal; refine
    # after a few real runs.
    baseline = report.get("completeness_baseline") or {}
    suggested = baseline.get("suggested_floor_per_run")
    observed = baseline.get("observed_total")
    if isinstance(suggested, int) and suggested > 0:
        lines.append(
            f"  expected_floor_per_run: {suggested}   "
            f"# measured at audit (~50% of {observed} observed); refine after first runs"
        )
    else:
        lines.append("  expected_floor_per_run: <edit-me — operator-set after first run>")

    lines.append("")
    lines.append("# ──────────────────────────────────────────────────────────────────────")
    lines.append("# Manual cross-check (~5 min) — no automated tool finds 100 % of a")
    lines.append("# publisher's discovery surfaces. Before committing, spend a few minutes")
    lines.append("# on the four checks below; they catch the surfaces this CLI cannot.")
    lines.append("# ──────────────────────────────────────────────────────────────────────")
    lines.append("#")
    lines.append("# A. Mediacloud registry (the canonical public source list).")
    lines.append("#    Search https://search.mediacloud.org for this publisher. If it is")
    lines.append("#    already catalogued, compare their curated feed list against the")
    lines.append("#    audit output above — any feed they have that we don't is a hint.")
    lines.append("#")
    lines.append("# B. Publisher footer / 'RSS' / 'Feed' / 'Newsletter' links.")
    lines.append("#    Open the homepage in a browser and scroll to the footer. Almost")
    lines.append("#    every news site exposes RSS / feed / newsletter / subscription")
    lines.append("#    links there. Some publishers (e.g. bundesregierung) host a")
    lines.append("#    multi-feed catalogue page at /service/newsletter-und-abos/...")
    lines.append("#    that auto-discovery cannot locate — but a human eye spots it in")
    lines.append("#    seconds.")
    lines.append("#")
    lines.append("# C. robots.txt — inspect by hand.")
    lines.append("#      curl -s <homepage>/robots.txt | grep -iE 'sitemap|feed|rss'")
    lines.append("#    The publisher may declare a Sitemap: directive pointing to a")
    lines.append("#    non-standard location this CLI did not probe (we hit the common")
    lines.append("#    paths, not every possible one).")
    lines.append("#")
    lines.append("# D. Distinguish format-duplicates from real coverage gains.")
    lines.append("#    If the audit found multiple feeds (e.g. .rss + ~atom.xml +")
    lines.append("#    ~rdf.xml all on the same path stem), they are usually format")
    lines.append("#    variants of the SAME article set — adding them all costs HTTP")
    lines.append("#    politeness budget without any coverage gain. Keep one format,")
    lines.append("#    drop the others. The publisher's RSS catalogue page (B) is what")
    lines.append("#    usually surfaces feeds with genuinely different content.")
    lines.append("#")
    lines.append("# Then:")
    lines.append("# 1. Edit the `article_url_pattern` regex(es) above to match the publisher's")
    lines.append("#    article URL convention (sample a few real article URLs to derive it).")
    lines.append("# 2. Verify the archive_index granularity by curling two distant dates.")
    lines.append("# 3. Run `make crawl-<probe-id>` and observe the per-channel telemetry to set")
    lines.append("#    `expected_floor_per_run` from the empirical baseline.")
    lines.append("#")
    lines.append("# Re-audit cadence: run `make audit-probe PROBE=<probe-id>` periodically")
    lines.append("# (e.g. weekly) — the diff workflow surfaces additive publisher-surface")
    lines.append("# drift without requiring this onboarding workflow to be repeated.")
    return "\n".join(lines)


def diff_against_configured(
    discovered: dict[str, list[str]],
    configured: dict[str, Any],
) -> dict[str, list[str]]:
    """Compare audit-discovered URL sets against the operator-configured
    ``discovery:`` block; return only the **additive** delta (URLs the
    audit surfaced that the configuration lacks).

    Removals are NEVER reported — publisher-surface disappearance is a
    methodological event (the underflow-alert telemetry handles it),
    not a routine maintenance trigger. The audit is conservative: an
    empty diff means "no NEW surfaces found", not "configuration is
    correct".

    Excludes URLs that the operator explicitly filtered (e.g.
    bundesregierung's three service-sitemaps are configured but the
    audit also returns them — they're not "new"). Also dedupes by
    canonical equivalence (trailing-slash, scheme).
    """
    def _canon(u: str) -> str:
        return u.rstrip("/").lower()

    diff: dict[str, list[str]] = {
        "sitemap_urls": [],
        "rss_hint_urls": [],
        "html_sitemap_urls": [],
        "archive_index_urls": [],
    }

    configured_sitemaps = {
        _canon(u) for u in (configured.get("sitemap_urls") or [])
    }
    for u in discovered.get("sitemap_urls", []):
        if _canon(u) not in configured_sitemaps:
            diff["sitemap_urls"].append(u)

    configured_rss = {
        _canon(u) for u in (configured.get("rss_hint_urls") or [])
    }
    # Forgive a legacy singular `rss_hint_url`.
    single = configured.get("rss_hint_url")
    if single:
        configured_rss.add(_canon(single))
    for u in discovered.get("rss_hint_urls", []):
        if _canon(u) not in configured_rss:
            diff["rss_hint_urls"].append(u)

    configured_html = {
        _canon(entry["url"] if isinstance(entry, dict) else entry)
        for entry in (configured.get("html_sitemap_urls") or [])
        if (entry.get("url") if isinstance(entry, dict) else entry)
    }
    for u in discovered.get("html_sitemap_urls", []):
        if _canon(u) not in configured_html:
            diff["html_sitemap_urls"].append(u)

    # Archive-index is a single block (url_template) per source, not a
    # list. We report it only if no archive_index block is configured AND
    # the audit found at least one.
    configured_archive = configured.get("archive_index")
    if not configured_archive:
        diff["archive_index_urls"] = list(discovered.get("archive_index_urls", []))

    return diff


def render_diff(diff: dict[str, list[str]], *, color: bool = True) -> str:
    """Render the additive diff as a human-readable string. If ``color``
    is true, additions are shown in ANSI green."""
    GREEN = "\033[32m" if color else ""
    BOLD = "\033[1m" if color else ""
    RESET = "\033[0m" if color else ""

    lines: list[str] = []
    total = 0
    for channel, urls in diff.items():
        if not urls:
            continue
        lines.append(f"{BOLD}{channel}{RESET}: {len(urls)} new")
        for url in urls:
            lines.append(f"  {GREEN}+ {url}{RESET}")
        total += len(urls)
    if total == 0:
        lines.append("(no new surfaces — configuration covers all audit-discovered URLs)")
    return "\n".join(lines)


def _prompt_yes_no(question: str, *, default_no: bool = True) -> bool:
    """Prompt the user with ``[y/N]`` (or ``[Y/n]`` if default_no is
    false). Empty input applies the default. Anything starting with
    ``y`` / ``j`` / ``Y`` / ``J`` is treated as yes. Non-interactive
    stdin (closed) returns the default."""
    suffix = "[y/N]" if default_no else "[Y/n]"
    try:
        answer = input(f"{question} {suffix} ").strip().lower()
    except EOFError:
        return not default_no
    if not answer:
        return not default_no
    return answer[0] in ("y", "j")


def apply_diff_to_yaml(
    yaml_path: Path,
    source_name: str,
    diff: dict[str, list[str]],
    *,
    backup_suffix: str = ".bak",
    pattern_samples: Optional[dict[str, dict[str, list[str]]]] = None,
    homepage_origin: Optional[str] = None,
) -> dict[str, int]:
    """Apply the additive diff to the named source's ``discovery:``
    block in ``yaml_path``. Preserves comments + formatting via
    ``ruamel.yaml``. Writes ``yaml_path.bak`` before mutating.

    Returns a dict ``{channel: count_added}`` for reporting.
    Idempotent: re-applying the same diff is a no-op.

    Pattern-Inferenz: ``pattern_samples`` maps html_sitemap / archive_index
    URLs to ``{"articles": [...], "non_articles": [...]}`` sample lists
    extracted by the audit. When supplied, the function calls
    :func:`infer_safe_pattern` for each new entry. A pattern is written
    to YAML only when it passes 100 % recall + 0 % false-positive on
    the sample (see :func:`infer_safe_pattern` for the safety contract).
    Otherwise the ``EDIT-ME-REGEX-MATCHING-ARTICLE-URLS`` placeholder
    remains — never a silently over-/under-matching pattern.
    """
    try:
        from ruamel.yaml import YAML  # type: ignore
    except ImportError as exc:
        raise RuntimeError(
            "ruamel.yaml is required for in-place YAML editing. "
            "Install with: pip install 'ruamel.yaml==0.18.*'"
        ) from exc

    yaml_rt = YAML(typ="rt")
    yaml_rt.preserve_quotes = True
    yaml_rt.indent(mapping=2, sequence=4, offset=2)

    with yaml_path.open("r", encoding="utf-8") as fh:
        data = yaml_rt.load(fh)

    sources = data.get("sources") or []
    target = None
    for src in sources:
        if src.get("name") == source_name:
            target = src
            break
    if target is None:
        raise ValueError(
            f"source {source_name!r} not found in {yaml_path}"
        )

    if "discovery" not in target or target["discovery"] is None:
        target["discovery"] = {}
    discovery = target["discovery"]

    added: dict[str, int] = {
        "sitemap_urls": 0,
        "rss_hint_urls": 0,
        "html_sitemap_urls": 0,
        "archive_index_urls": 0,
    }

    def _ensure_list(key: str) -> Any:
        if key not in discovery or discovery[key] is None:
            discovery[key] = []
        return discovery[key]

    for url in diff.get("sitemap_urls") or []:
        lst = _ensure_list("sitemap_urls")
        if url not in lst:
            lst.append(url)
            added["sitemap_urls"] += 1
    for url in diff.get("rss_hint_urls") or []:
        lst = _ensure_list("rss_hint_urls")
        if url not in lst:
            lst.append(url)
            added["rss_hint_urls"] += 1
    def _safe_pattern_for(url: str) -> str:
        """Return an inferred article_url_pattern if and only if it
        passes the strict 100 %-recall / 0 %-FP safety gate against the
        observed sample. Otherwise return the EDIT-ME placeholder."""
        if not pattern_samples or not homepage_origin:
            return "EDIT-ME-REGEX-MATCHING-ARTICLE-URLS"
        sample = pattern_samples.get(url)
        if not sample:
            return "EDIT-ME-REGEX-MATCHING-ARTICLE-URLS"
        pattern, _diag = infer_safe_pattern(
            sample.get("articles") or [],
            sample.get("non_articles") or [],
            homepage_origin,
        )
        return pattern or "EDIT-ME-REGEX-MATCHING-ARTICLE-URLS"

    for url in diff.get("html_sitemap_urls") or []:
        lst = _ensure_list("html_sitemap_urls")
        existing_urls = {
            (e.get("url") if isinstance(e, dict) else e)
            for e in lst
        }
        if url not in existing_urls:
            # The pattern is either the safety-gated auto-inferred regex
            # (100 % recall, 0 % false-positive on observed sample) OR
            # the EDIT-ME placeholder. There is no in-between — silent
            # over/under-matching is structurally excluded. The
            # placeholder is a syntactically invalid regex on purpose
            # so the crawler refuses to ingest the channel until a
            # real pattern is provided.
            lst.append({
                "url": url,
                "article_url_pattern": _safe_pattern_for(url),
            })
            added["html_sitemap_urls"] += 1
    # archive_index is a single block, not a list; we never overwrite
    # an existing one, only suggest the first audit-discovered template.
    if diff.get("archive_index_urls") and not discovery.get("archive_index"):
        first = diff["archive_index_urls"][0]
        # Strip the origin so the operator sees a clean url_template.
        parsed = urlparse(first)
        path_template = parsed.path
        if parsed.query:
            path_template += "?" + parsed.query
        discovery["archive_index"] = {
            "url_template": f"{parsed.scheme}://{parsed.netloc}{path_template}",
            "date_format": "%Y-%m-%d",
            "granularity": "daily",
            "article_url_pattern": _safe_pattern_for(first),
        }
        added["archive_index_urls"] = 1

    # Backup, then write.
    backup_path = yaml_path.with_suffix(yaml_path.suffix + backup_suffix)
    shutil.copy2(yaml_path, backup_path)
    with yaml_path.open("w", encoding="utf-8") as fh:
        yaml_rt.dump(data, fh)
    return added


def _load_sources_yaml(yaml_path: Path) -> dict[str, Any]:
    """Read a probe's ``sources.yaml`` and return the parsed dict."""
    import yaml as _yaml
    with yaml_path.open("r", encoding="utf-8") as fh:
        return _yaml.safe_load(fh) or {}


def _find_source_block(data: dict[str, Any], name: str) -> Optional[dict[str, Any]]:
    for src in data.get("sources") or []:
        if src.get("name") == name:
            return src
    return None


