// Package apicontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apicontract

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// HealthStatus Health probe payload. `/healthz` returns `{"status":"alive"}`; `/readyz` returns a map of each dependency to `ok` or `unavailable`.
type HealthStatus map[string]string

// IngestResult Per-batch ingestion outcome. `failed > 0` produces a 207 Multi-Status response so the crawler can retry only the offending documents.
type IngestResult struct {
	// Failed Number of documents that failed to persist.
	Failed int32 `json:"failed"`

	// JobId Numeric identifier of the ingestion job in PostgreSQL.
	JobId int32 `json:"job_id"`

	// Uploaded Number of documents successfully persisted to Bronze.
	Uploaded int32 `json:"uploaded"`
}

// SourceLookup Resolved source record for the requested `name`.
type SourceLookup struct {
	// Id Numeric source identifier used by `/ingest`.
	Id int32 `json:"id"`

	// Name Canonical source name (e.g., `tagesschau`).
	Name string `json:"name"`
}

// IngestDocumentsJSONBody defines parameters for IngestDocuments.
type IngestDocumentsJSONBody struct {
	// Documents Documents to ingest. Empty arrays are rejected with 400.
	Documents []struct {
		// Data Raw document payload. Passed through to Bronze without interpretation. Typically a JSON object, but any JSON value is accepted.
		Data interface{} `json:"data"`

		// Key Deterministic object key under the configured source prefix in MinIO Bronze (e.g., `news/wikipedia/2026-04-19T12-00-00Z.json`). Must be stable across retries to preserve storage-level idempotency.
		Key string `json:"key"`
	} `json:"documents"`

	// SourceId Numeric identifier of the source in the PostgreSQL `sources` table. Resolve the ID via `GET /sources?name=<name>` — crawlers should not hardcode IDs.
	SourceId int32 `json:"source_id"`
}

// GetSourceByNameParams defines parameters for GetSourceByName.
type GetSourceByNameParams struct {
	// Name Canonical source name (as seeded in PostgreSQL).
	Name string `form:"name" json:"name"`
}

// IngestDocumentsJSONRequestBody defines body for IngestDocuments for application/json ContentType.
type IngestDocumentsJSONRequestBody IngestDocumentsJSONBody
