<script lang="ts">
  // Phase 122g — per-channel discovery telemetry panel on the Probe
  // Dossier (Surface II foundation, Brief §4.2.1). Sibling to the
  // Phase 122f MetadataCoveragePanel — both surface a publisher's
  // emission posture as a queryable runtime signal so coverage
  // degradation is visible immediately rather than silently
  // accumulating across crawl runs.
  //
  // ADR-031 records the DiscoveryProtocol Contract this panel
  // visualises. WP-003 §3.2 + Probe-0 Structural Bias #8 provide the
  // methodological frame: cross-source corpus-volume comparisons
  // reflect crawler access, not publication frequency — the
  // dashboard MUST render that distinction so the consumer can
  // interpret aggregate panels honestly.
  //
  // Negative-Space integration (Brief §7.7): when a channel's
  // underflow-alert is active, the panel renders the methodological-
  // register prose explaining the publisher-side cause (sitemap.xml
  // started returning 404, an RSS feed retired, the archive endpoint
  // moved) rather than collapsing to a silent missing-data placeholder.
  //
  // NOTE TO INTEGRATOR: this panel depends on TypeScript types
  // generated by `make fe-codegen` after Phase 122g's OpenAPI changes
  // land. The query helper `sourceDiscoveryCoverageQuery` and its
  // typed response shape `DiscoveryCoverageResponseDto` are added in
  // the same codegen pass that wires the BFF handler.
  import { createQuery } from '@tanstack/svelte-query';
  import {
    sourceDiscoveryCoverageQuery,
    type FetchContext,
    type DiscoveryCoverageResponseDto,
    type DiscoveryCoveragePerChannelDto,
    type QueryOutcome
  } from '$lib/api/queries';
  import { m } from '$lib/paraglide/messages.js';
  import { formatNumber } from '$lib/localization/format';
  import NegativeSpaceBadge from '$lib/components/base/NegativeSpaceBadge.svelte';

  // Phase 148d — render a 0..1 ratio as a whole-number percent for the
  // completeness headline + the funnel rates (WP-007 §4.1, §4.3).
  const pct = (ratio: number): number => Math.round(ratio * 100);

  interface Props {
    sourceId: string;
    windowDays?: number;
    ctx?: FetchContext;
  }

  let { sourceId, windowDays, ctx = { baseUrl: '/api/v1' } }: Props = $props();

  const query = createQuery<
    QueryOutcome<DiscoveryCoverageResponseDto>,
    Error,
    QueryOutcome<DiscoveryCoverageResponseDto>
  >(() => {
    const o = sourceDiscoveryCoverageQuery(ctx, sourceId, windowDays);
    return { queryKey: [...o.queryKey], queryFn: o.queryFn, staleTime: o.staleTime };
  });

  // Channel display order: highest-volume first by convention, with
  // platform-agnostic channels (sitemap, rss) before web-specific
  // ones (html_sitemap, archive_index). Future Twitter/Reddit/etc.
  // channels are appended at runtime in receive order.
  const CHANNEL_ORDER: ReadonlyArray<string> = ['sitemap', 'rss', 'html_sitemap', 'archive_index'];

  const CHANNEL_LABELS: Record<string, () => string> = {
    sitemap: m.source_channel_sitemap,
    rss: m.source_channel_rss,
    html_sitemap: m.source_channel_html_sitemap,
    archive_index: m.source_channel_archive_index
  };

  // The methodological-register prose surfaced when a channel underflow
  // alert is active. Phase 144 — sourced from the per-locale Paraglide
  // `source` catalogue (keyed by channel name).
  const UNDERFLOW_PROSE: Record<string, () => string> = {
    sitemap: m.source_underflow_sitemap,
    rss: m.source_underflow_rss,
    html_sitemap: m.source_underflow_html_sitemap,
    archive_index: m.source_underflow_archive_index
  };

  function orderedChannels(
    payload: DiscoveryCoverageResponseDto
  ): DiscoveryCoveragePerChannelDto[] {
    // Plain object keyed by channel name — non-reactive local lookup.
    // (Avoiding `Map` here keeps `svelte/prefer-svelte-reactivity` happy
    // without needing SvelteMap; this function is pure render-time.)
    const byName: Record<string, DiscoveryCoveragePerChannelDto> = {};
    for (const c of payload.perChannel) byName[c.channel] = c;

    const ordered: DiscoveryCoveragePerChannelDto[] = [];
    for (const channel of CHANNEL_ORDER) {
      const entry = byName[channel];
      if (entry) {
        ordered.push(entry);
        delete byName[channel];
      }
    }
    // Trailing entries — channels we haven't seen before (future
    // platform-class crawlers contribute new names without schema
    // changes).
    for (const channel of Object.keys(byName)) {
      const entry = byName[channel];
      if (entry) ordered.push(entry);
    }
    return ordered;
  }
</script>

<section class="discovery-coverage-panel" aria-labelledby="discovery-coverage-heading">
  <header>
    <h3 id="discovery-coverage-heading">{m.source_discovery_heading()}</h3>
    <p class="lede">{m.source_discovery_lede()}</p>
    <details class="how-to-read">
      <summary>{m.source_discovery_howto_summary()}</summary>
      <dl>
        <dt>{m.source_discovery_howto_discovered_dt()}</dt>
        <dd>{m.source_discovery_howto_discovered_dd()}</dd>
        <dt>{m.source_discovery_howto_dedup_dt()}</dt>
        <dd>
          {m.source_discovery_howto_dedup_dd_lead()}
          <em>{m.source_discovery_howto_dedup_dd_em()}</em
          >{m.source_discovery_howto_dedup_dd_tail()}
        </dd>
        <dt>{m.source_discovery_howto_avg_dt()}</dt>
        <dd>{m.source_discovery_howto_avg_dd()}</dd>
      </dl>
    </details>
  </header>

  {#if query.isPending}
    <p class="loading">{m.source_discovery_loading()}</p>
  {:else if query.isError}
    <p class="error">{m.source_discovery_error()}</p>
  {:else if query.data?.kind === 'success'}
    {@const payload = query.data.data}
    <dl class="summary">
      <div>
        <dt>{m.source_discovery_summary_window()}</dt>
        <dd>{m.source_discovery_summary_window_value({ days: payload.windowDays })}</dd>
      </div>
      <div>
        <dt>{m.source_discovery_summary_total_urls()}</dt>
        <dd>{formatNumber(payload.totalUrlsDiscoveredLastRun)}</dd>
      </div>
      <div>
        <dt>{m.source_discovery_summary_unique()}</dt>
        <dd>{formatNumber(payload.uniqueUrlsAfterDedupLastRun)}</dd>
      </div>
      {#if payload.expectedFloorPerRun != null}
        <div>
          <dt>{m.source_discovery_summary_floor()}</dt>
          <dd>{formatNumber(payload.expectedFloorPerRun)}</dd>
        </div>
      {/if}
    </dl>

    <!-- Phase 148d (WP-007 §4.1, §7) — completeness travels WITH the data:
         a reader cannot read this source's corpus without seeing how complete
         it is. The badge is neutral methodological-register, never a warning. -->
    <div class="completeness" class:indeterminate={payload.completenessIndeterminate}>
      {#if payload.completenessIndeterminate}
        <div class="completeness-head">
          <NegativeSpaceBadge nsClass="collection_completeness" size="md" showLabel showInfo />
        </div>
        <p class="ns-prose">{m.source_completeness_indeterminate()}</p>
      {:else if payload.completeness != null}
        <div class="completeness-head">
          <NegativeSpaceBadge nsClass="collection_completeness" size="md" showInfo />
          <span class="pct">{m.source_completeness_value({ pct: pct(payload.completeness) })}</span>
          <span class="muted"
            >{m.source_completeness_against({
              measured: payload.perChannel.length - (payload.indeterminateChannelCount ?? 0),
              total: payload.perChannel.length
            })}</span
          >
        </div>
        {#if (payload.indeterminateChannelCount ?? 0) > 0}
          <p class="ns-prose">
            {m.source_completeness_remainder({ n: payload.indeterminateChannelCount ?? 0 })}
          </p>
        {/if}
      {/if}

      {#if payload.funnel?.present}
        {@const f = payload.funnel}
        <details class="funnel">
          <summary>{m.source_funnel_summary()}</summary>
          <dl>
            {#if payload.declaredTotalLastRun != null}
              <div>
                <dt>{m.source_funnel_stage_declared()}</dt>
                <dd>{formatNumber(payload.declaredTotalLastRun)}</dd>
              </div>
            {/if}
            <div>
              <dt>{m.source_funnel_stage_discovered()}</dt>
              <dd>{formatNumber(f.discovered ?? 0)}</dd>
            </div>
            <div>
              <dt>{m.source_funnel_stage_already_collected()}</dt>
              <dd>{formatNumber(f.alreadyCollected ?? 0)}</dd>
            </div>
            <div>
              <dt>{m.source_funnel_stage_fetched()}</dt>
              <dd>{formatNumber(f.fetched ?? 0)}</dd>
            </div>
            <div>
              <dt>{m.source_funnel_stage_thin()}</dt>
              <dd>{formatNumber(f.thinContentDropped ?? 0)}</dd>
            </div>
            <div>
              <dt>{m.source_funnel_stage_submitted()}</dt>
              <dd>{formatNumber(f.submitted ?? 0)}</dd>
            </div>
            <div>
              <dt>{m.source_funnel_stage_gold()}</dt>
              <dd>{formatNumber(f.goldRows ?? 0)}</dd>
            </div>
          </dl>
          <p class="funnel-rates">
            {#if f.extractionSuccessRate != null}
              <span>{m.source_funnel_rate_extraction({ pct: pct(f.extractionSuccessRate) })}</span>
            {/if}
            {#if f.nonArticleRate != null}
              <span class="muted"
                >{m.source_funnel_rate_nonarticle({ pct: pct(f.nonArticleRate) })}</span
              >
            {/if}
          </p>
        </details>
      {/if}
    </div>

    <ul class="channels">
      {#each orderedChannels(payload) as channel (channel.channel)}
        <li class="channel" class:underflow={channel.underflowAlertActive}>
          <div class="channel-row">
            <span class="channel-label"
              >{(CHANNEL_LABELS[channel.channel] ?? (() => channel.channel))()}</span
            >
            <span class="channel-counts">
              {#if channel.declared != null}
                <span class="muted"
                  >{channel.declaredIndeterminate
                    ? m.source_channel_declared_indeterminate({
                        n: formatNumber(channel.declared)
                      })
                    : m.source_channel_declared({ n: formatNumber(channel.declared) })}</span
                >
              {/if}
              {m.source_discovery_channel_counts({
                discovered: formatNumber(channel.lastRunUrlsDiscovered)
              })}
              <span class="muted"
                >{m.source_discovery_channel_dedup({
                  count: formatNumber(channel.lastRunUrlsAfterDedup)
                })}</span
              >
              <span class="muted"
                >{m.source_discovery_channel_avg({
                  value: channel.averageUrlsDiscoveredPerRun.toFixed(1)
                })}</span
              >
            </span>
          </div>
          {#if channel.underflowAlertActive}
            <p class="negative-space-prose">
              {(UNDERFLOW_PROSE[channel.channel] ?? m.source_discovery_underflow_fallback)()}
            </p>
          {/if}
        </li>
      {/each}
    </ul>
  {:else}
    <p class="empty">{m.source_discovery_empty()}</p>
  {/if}
</section>

<style>
  .discovery-coverage-panel {
    border: 1px solid var(--border-subtle, #2a2a2a);
    border-radius: 6px;
    padding: 1rem 1.25rem;
    background: var(--panel-bg, transparent);
  }
  h3 {
    margin: 0 0 0.25rem 0;
    font-size: 1rem;
    font-weight: 600;
  }
  .lede {
    margin: 0 0 0.5rem 0;
    color: var(--text-muted, #888);
    font-size: 0.85rem;
  }
  .how-to-read {
    margin: 0 0 1rem 0;
    font-size: 0.8rem;
    color: var(--text-muted, #888);
  }
  .how-to-read summary {
    cursor: pointer;
    color: var(--color-fg-muted, #aaa);
    user-select: none;
  }
  .how-to-read summary:hover {
    color: var(--color-fg, #ddd);
  }
  .how-to-read dl {
    margin: 0.5rem 0 0 0;
    padding: 0.5rem 0.75rem;
    background: var(--color-bg-elevated, rgba(255, 255, 255, 0.02));
    border-left: 2px solid var(--border-subtle, #2a2a2a);
    border-radius: 2px;
  }
  .how-to-read dt {
    font-weight: 600;
    color: var(--color-fg-muted, #bbb);
    margin-top: 0.5rem;
  }
  .how-to-read dt:first-of-type {
    margin-top: 0;
  }
  .how-to-read dd {
    margin: 0.15rem 0 0 0;
    line-height: 1.4;
  }
  .summary {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
    gap: 0.5rem 1rem;
    margin: 0 0 1rem 0;
  }
  .summary > div {
    display: flex;
    flex-direction: column;
  }
  .summary dt {
    color: var(--text-muted, #888);
    font-size: 0.75rem;
  }
  .summary dd {
    margin: 0;
    font-size: 1rem;
    font-variant-numeric: tabular-nums;
  }
  .completeness {
    margin: 0 0 1rem 0;
    padding: 0.5rem 0.75rem;
    background: var(--color-bg-elevated, rgba(255, 255, 255, 0.02));
    border-left: 2px solid var(--border-subtle, #2a2a2a);
    border-radius: 2px;
  }
  .completeness-head {
    display: flex;
    align-items: baseline;
    gap: 0.5rem;
    flex-wrap: wrap;
  }
  .completeness .pct {
    font-size: 1rem;
    font-weight: 600;
    font-variant-numeric: tabular-nums;
  }
  .ns-prose {
    margin: 0.35rem 0 0 0;
    color: var(--text-muted, #aaa);
    font-size: 0.82rem;
    line-height: 1.4;
  }
  .funnel {
    margin: 0.5rem 0 0 0;
    font-size: 0.82rem;
  }
  .funnel summary {
    cursor: pointer;
    color: var(--color-fg-muted, #aaa);
    user-select: none;
  }
  .funnel dl {
    display: grid;
    grid-template-columns: 1fr auto;
    gap: 0.15rem 1rem;
    margin: 0.5rem 0 0 0;
  }
  .funnel dt {
    color: var(--text-muted, #888);
  }
  .funnel dd {
    margin: 0;
    text-align: right;
    font-variant-numeric: tabular-nums;
  }
  .funnel-rates {
    display: flex;
    gap: 1rem;
    margin: 0.5rem 0 0 0;
    font-variant-numeric: tabular-nums;
  }
  .channels {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }
  .channel {
    border-left: 3px solid transparent;
    padding-left: 0.75rem;
  }
  .channel.underflow {
    border-left-color: var(--alert-color, #c04040);
  }
  .channel-row {
    display: flex;
    justify-content: space-between;
    gap: 1rem;
    align-items: baseline;
    font-variant-numeric: tabular-nums;
  }
  .channel-label {
    font-weight: 500;
  }
  .muted {
    color: var(--text-muted, #888);
    margin-left: 0.5rem;
  }
  .negative-space-prose {
    margin: 0.25rem 0 0 0;
    color: var(--text-muted, #aaa);
    font-size: 0.85rem;
    font-style: italic;
  }
  .loading,
  .error,
  .empty {
    color: var(--text-muted, #888);
    margin: 0;
  }
</style>
