<script lang="ts">
  // Phase 122g — per-channel discovery telemetry panel on the Probe
  // Dossier (Surface II foundation, Brief §4.2.1). Sibling to the
  // Phase 122f MetadataCoveragePanel — both surface a publisher's
  // emission posture as a queryable runtime signal so coverage
  // degradation is visible immediately rather than silently
  // accumulating across crawl runs.
  //
  // ADR-031 records the DiscoveryProtocol Contract this panel
  // visualises. WP-003 §3.2 + Probe-0 Structural Bias #8 provide the
  // methodological frame: cross-source corpus-volume comparisons
  // reflect crawler access, not publication frequency — the
  // dashboard MUST render that distinction so the consumer can
  // interpret aggregate panels honestly.
  //
  // Negative-Space integration (Brief §7.7): when a channel's
  // underflow-alert is active, the panel renders the methodological-
  // register prose explaining the publisher-side cause (sitemap.xml
  // started returning 404, an RSS feed retired, the archive endpoint
  // moved) rather than collapsing to a silent missing-data placeholder.
  //
  // NOTE TO INTEGRATOR: this panel depends on TypeScript types
  // generated by `make fe-codegen` after Phase 122g's OpenAPI changes
  // land. The query helper `sourceDiscoveryCoverageQuery` and its
  // typed response shape `DiscoveryCoverageResponseDto` are added in
  // the same codegen pass that wires the BFF handler.
  import { createQuery } from '@tanstack/svelte-query';
  import {
    sourceDiscoveryCoverageQuery,
    type FetchContext,
    type DiscoveryCoverageResponseDto,
    type DiscoveryCoveragePerChannelDto,
    type QueryOutcome
  } from '$lib/api/queries';

  interface Props {
    sourceId: string;
    windowDays?: number;
    ctx?: FetchContext;
  }

  let { sourceId, windowDays, ctx = { baseUrl: '/api/v1' } }: Props = $props();

  const query = createQuery<
    QueryOutcome<DiscoveryCoverageResponseDto>,
    Error,
    QueryOutcome<DiscoveryCoverageResponseDto>
  >(() => {
    const o = sourceDiscoveryCoverageQuery(ctx, sourceId, windowDays);
    return { queryKey: [...o.queryKey], queryFn: o.queryFn, staleTime: o.staleTime };
  });

  // Channel display order: highest-volume first by convention, with
  // platform-agnostic channels (sitemap, rss) before web-specific
  // ones (html_sitemap, archive_index). Future Twitter/Reddit/etc.
  // channels are appended at runtime in receive order.
  const CHANNEL_ORDER: ReadonlyArray<string> = ['sitemap', 'rss', 'html_sitemap', 'archive_index'];

  const CHANNEL_LABELS: Record<string, string> = {
    sitemap: 'XML Sitemap',
    rss: 'RSS / Atom feeds',
    html_sitemap: 'HTML sitemap page',
    archive_index: 'Date-indexed archive walker'
  };

  // The methodological-register prose surfaced when a channel
  // underflow alert is active. Static binding (per Phase 122f's
  // FIELD_PROSE pattern) — promoted to the Content Catalog if a
  // multilingual variant lands later.
  const UNDERFLOW_PROSE: Record<string, string> = {
    sitemap:
      "The publisher's XML sitemap surfaced fewer URLs than the configured floor. " +
      'Likely cause: the sitemap moved, the publisher started returning 404, or a ' +
      'service-sitemap-only configuration started filtering harder. Run audit-source-discovery to re-verify the surface.',
    rss:
      "The publisher's RSS feed(s) surfaced fewer URLs than expected. " +
      'Likely cause: a feed retired, the catalogue page restructured, or the publisher reduced their feed catalogue. ' +
      "Cross-check the publisher's /service/newsletter or equivalent feeds page.",
    html_sitemap:
      'The HTML sitemap page surfaced fewer article-shaped links than expected. ' +
      'Likely cause: the page moved, the HTML structure changed, or the article-URL regex no longer matches. ' +
      'Re-derive the `article_url_pattern` from a fresh sample of real article URLs.',
    archive_index:
      'The date-indexed archive walker surfaced fewer articles than expected. ' +
      'Likely cause: the publisher changed the URL pattern, the date format, or the per-day article volume. ' +
      'Sample two distant dates manually to verify the endpoint still works.'
  };

  function orderedChannels(
    payload: DiscoveryCoverageResponseDto
  ): DiscoveryCoveragePerChannelDto[] {
    // Plain object keyed by channel name — non-reactive local lookup.
    // (Avoiding `Map` here keeps `svelte/prefer-svelte-reactivity` happy
    // without needing SvelteMap; this function is pure render-time.)
    const byName: Record<string, DiscoveryCoveragePerChannelDto> = {};
    for (const c of payload.perChannel) byName[c.channel] = c;

    const ordered: DiscoveryCoveragePerChannelDto[] = [];
    for (const channel of CHANNEL_ORDER) {
      const entry = byName[channel];
      if (entry) {
        ordered.push(entry);
        delete byName[channel];
      }
    }
    // Trailing entries — channels we haven't seen before (future
    // platform-class crawlers contribute new names without schema
    // changes).
    for (const channel of Object.keys(byName)) {
      const entry = byName[channel];
      if (entry) ordered.push(entry);
    }
    return ordered;
  }
</script>

<section class="discovery-coverage-panel" aria-labelledby="discovery-coverage-heading">
  <header>
    <h3 id="discovery-coverage-heading">Discovery coverage</h3>
    <p class="lede">
      Every crawl pass asks each publisher channel (XML sitemap, RSS feed, HTML sitemap pages,
      date-indexed archive walker) which articles exist in the recent window. This panel shows what
      the most recent pass actually returned, per channel.
    </p>
    <details class="how-to-read">
      <summary>How to read these numbers</summary>
      <dl>
        <dt>Discovered</dt>
        <dd>Raw count of article URLs the channel returned in this pass — before any cleanup.</dd>
        <dt>Dedup → N</dt>
        <dd>
          Of the discovered URLs, how many were unique to this channel <em
            >within this single pass</em
          >. The first channel to surface a URL gets credit; later channels that hit the same URL
          report it as discovered but not as dedup-unique. Strong overlap (low dedup number for the
          richer channel) means the publisher's surfaces agree about which articles exist — this is
          the healthy case. It does NOT mean articles are being skipped; the crawl still fetches
          every unique URL.
        </dd>
        <dt>Avg</dt>
        <dd>
          Trailing-window average of the discovered count. Sudden drops vs avg are the publisher
          changing its discovery surface (sitemap broken, archive truncated, RSS format change) and
          are flagged as an underflow.
        </dd>
      </dl>
    </details>
  </header>

  {#if query.isPending}
    <p class="loading">Loading discovery telemetry…</p>
  {:else if query.isError}
    <p class="error">Discovery coverage temporarily unavailable.</p>
  {:else if query.data?.kind === 'success'}
    {@const payload = query.data.data}
    <dl class="summary">
      <div>
        <dt>Window</dt>
        <dd>{payload.windowDays} days</dd>
      </div>
      <div>
        <dt>Total URLs (last run)</dt>
        <dd>{payload.totalUrlsDiscoveredLastRun}</dd>
      </div>
      <div>
        <dt>Unique after dedup</dt>
        <dd>{payload.uniqueUrlsAfterDedupLastRun}</dd>
      </div>
      {#if payload.expectedFloorPerRun != null}
        <div>
          <dt>Expected floor</dt>
          <dd>{payload.expectedFloorPerRun}</dd>
        </div>
      {/if}
    </dl>

    <ul class="channels">
      {#each orderedChannels(payload) as channel (channel.channel)}
        <li class="channel" class:underflow={channel.underflowAlertActive}>
          <div class="channel-row">
            <span class="channel-label">{CHANNEL_LABELS[channel.channel] ?? channel.channel}</span>
            <span class="channel-counts">
              {channel.lastRunUrlsDiscovered} discovered
              <span class="muted">(dedup → {channel.lastRunUrlsAfterDedup})</span>
              <span class="muted">avg {channel.averageUrlsDiscoveredPerRun.toFixed(1)}</span>
            </span>
          </div>
          {#if channel.underflowAlertActive}
            <p class="negative-space-prose">
              {UNDERFLOW_PROSE[channel.channel] ?? 'Discovery underflow active for this channel.'}
            </p>
          {/if}
        </li>
      {/each}
    </ul>
  {:else}
    <p class="empty">No discovery telemetry yet — first crawl run pending.</p>
  {/if}
</section>

<style>
  .discovery-coverage-panel {
    border: 1px solid var(--border-subtle, #2a2a2a);
    border-radius: 6px;
    padding: 1rem 1.25rem;
    background: var(--panel-bg, transparent);
  }
  h3 {
    margin: 0 0 0.25rem 0;
    font-size: 1rem;
    font-weight: 600;
  }
  .lede {
    margin: 0 0 0.5rem 0;
    color: var(--text-muted, #888);
    font-size: 0.85rem;
  }
  .how-to-read {
    margin: 0 0 1rem 0;
    font-size: 0.8rem;
    color: var(--text-muted, #888);
  }
  .how-to-read summary {
    cursor: pointer;
    color: var(--color-fg-muted, #aaa);
    user-select: none;
  }
  .how-to-read summary:hover {
    color: var(--color-fg, #ddd);
  }
  .how-to-read dl {
    margin: 0.5rem 0 0 0;
    padding: 0.5rem 0.75rem;
    background: var(--color-bg-elevated, rgba(255, 255, 255, 0.02));
    border-left: 2px solid var(--border-subtle, #2a2a2a);
    border-radius: 2px;
  }
  .how-to-read dt {
    font-weight: 600;
    color: var(--color-fg-muted, #bbb);
    margin-top: 0.5rem;
  }
  .how-to-read dt:first-of-type {
    margin-top: 0;
  }
  .how-to-read dd {
    margin: 0.15rem 0 0 0;
    line-height: 1.4;
  }
  .summary {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
    gap: 0.5rem 1rem;
    margin: 0 0 1rem 0;
  }
  .summary > div {
    display: flex;
    flex-direction: column;
  }
  .summary dt {
    color: var(--text-muted, #888);
    font-size: 0.75rem;
  }
  .summary dd {
    margin: 0;
    font-size: 1rem;
    font-variant-numeric: tabular-nums;
  }
  .channels {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }
  .channel {
    border-left: 3px solid transparent;
    padding-left: 0.75rem;
  }
  .channel.underflow {
    border-left-color: var(--alert-color, #c04040);
  }
  .channel-row {
    display: flex;
    justify-content: space-between;
    gap: 1rem;
    align-items: baseline;
    font-variant-numeric: tabular-nums;
  }
  .channel-label {
    font-weight: 500;
  }
  .muted {
    color: var(--text-muted, #888);
    margin-left: 0.5rem;
  }
  .negative-space-prose {
    margin: 0.25rem 0 0 0;
    color: var(--text-muted, #aaa);
    font-size: 0.85rem;
    font-style: italic;
  }
  .loading,
  .error,
  .empty {
    color: var(--text-muted, #888);
    margin: 0;
  }
</style>
