-- AĒR PostgreSQL Initialization Stub
--
-- Schema creation and seeding are now managed by golang-migrate.
-- Versioned migration files live in infra/postgres/migrations/.
-- The ingestion-api runs migrations on startup before serving traffic.
--
-- This file is retained for backward compatibility with the Docker
-- entrypoint convention but is intentionally a no-op.