-- Seed: metric_validity scaffold for sentiment_score_sentiws.
-- Phase 117: NLP Hardening — Sentiment Tier 1 Improvements (WP-002).
--
-- One-off dev-setup script — NOT a runtime migration. Intentionally a NO-OP
-- on the live schema.
--
-- The roadmap entry asked for a scaffold row with "validation_status =
-- unvalidated" and an error_taxonomy JSON listing the resolved/open WP-002
-- §3.2 limitations. The actual `aer_gold.metric_validity` schema, however,
-- does NOT carry a `validation_status` column — the BFF derives that string
-- from `valid_until`:
--   no row at all       → "unvalidated"   (← the correct state for Phase 117)
--   row, valid_until>now → "validated"
--   row, valid_until<now → "expired"
--
-- Inserting a scaffold row therefore would either (a) misreport the metric
-- as `validated` (future valid_until), or (b) misreport it as `expired`
-- (past valid_until). Neither matches the roadmap's stated intent. The
-- correct on-disk state for an unvalidated metric is the absence of a row.
--
-- The known-limitations payload that the roadmap wanted to attach lives in
-- `docs/methodology/en/WP-002-en-metric_validity_and_sentiment_calibration.md`
-- §3.2 (where the resolved-vs-open breakdown is now narrative), and in
-- this file as a documentation block — it does not need to be in
-- ClickHouse until an actual annotation study (WP-002 §6.2) populates
-- `alpha_score`, `correlation`, `n_annotated`, and a meaningful
-- `valid_until`.
--
-- Reference (for the future annotation-study reviewer who will fill in
-- `alpha_score` and `valid_until`):
--
--   metric_name : sentiment_score_sentiws
--   context_key : de:rss:epistemic_authority
--   tier        : 1 (Tier 1, deterministic SentiWS)
--   resolved    : negation_blindness_phase117,
--                 compound_decomposition_phase117
--   open        : irony, sarcasm, domain_dependency,
--                 compositionality_beyond_compounds, lexicon_currency
--
-- This file is checked in for auditability and runs as a no-op SELECT, so
-- piping it into clickhouse-client succeeds without changing state.
--
-- ---------------------------------------------------------------------------
-- Phase 118 addendum: entity_link_confidence (cross-context)
-- ---------------------------------------------------------------------------
--
-- The Wikidata entity-linking step writes one row per linked NER span to
-- `aer_gold.entity_links` with `link_confidence ∈ {1.0, 0.85, 0.7}`. These
-- weights are heuristic Tier-1.5 engineering defaults (label / altLabel /
-- accent-fold matches respectively). They have NOT been validated against
-- a precision/recall annotation study; the appropriate `metric_validity`
-- state is therefore "unvalidated".
--
-- Per the Phase 117 convention above, "unvalidated" is encoded as the
-- ABSENCE of a `metric_validity` row, not a placeholder INSERT. The block
-- below documents the open failure modes for the future annotation-study
-- reviewer; the actual `aer_gold.metric_validity` table stays untouched
-- by this seed.
--
-- `entity_link_confidence` is a CROSS-CONTEXT metric — the same heuristic
-- weights apply to every (language, source_type, discourse_function)
-- triple. Phase 118a's manifest-driven scaffold generator will only
-- auto-emit per-language rows; cross-context entries like this one stay
-- hand-maintained as documentation.
--
--   metric_name : entity_link_confidence
--   context_key : *:*:*    (cross-context — heuristic is language-agnostic)
--   tier        : 1.5      (alias-index lookup, not validated linker)
--   open_failure_modes:
--     - heuristic confidence weights (1.0 / 0.85 / 0.7) for label / altLabel /
--       accent-fold matches are engineering defaults pending the WP-002 §4.2
--       annotation study
--     - sitelink-tiebreaker may favour outdated entity references (the
--       Wikidata page rank does not encode "currently in office")
--     - alias collisions across language boundaries are not measured —
--       the language-scoped lookup mitigates but does not eliminate
--     - no precision/recall measurement on Probe 0 corpus; the sample
--       is qualitative until the annotation study runs
--   resolution_path:
--     A future Tier-2 phase (gated on annotation study) will measure
--     precision/recall, replace or recalibrate the confidence weights, and
--     consider a transformer-based linker (BLINK / ReFinED / mGENRE) if
--     disambiguation precision proves insufficient.

SELECT 'metric_validity_scaffold: no-op — see file header for rationale' AS note;
