import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import ts from 'typescript-eslint';
import prettier from 'eslint-config-prettier';
import svelteConfig from './svelte.config.js';

export default ts.config(
  js.configs.recommended,
  ...ts.configs.recommended,
  ...svelte.configs.recommended,
  prettier,
  ...svelte.configs.prettier,
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node
      }
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }
      ],
      // Retired-vocabulary ratchet (Phase 140). Bans the old domain terms from
      // re-entering the code as identifiers or user-facing strings. Comments are
      // not AST nodes, so legitimate historical "retired X" notes are untouched.
      // The lowercase URL key 'viewMode' is a contract (legacy /lanes/ redirect)
      // and stays — it is a string Literal but does not match these patterns.
      // See docs/development/conventions.md §1.
      'no-restricted-syntax': [
        'error',
        {
          selector: 'Identifier[name=/^(ViewMode|ViewingMode|WorkbenchScopeBar)/]',
          message:
            'Retired vocabulary (Phase 140): use `Presentation` (not ViewMode) and `PillarId` (not ViewingMode); the WorkbenchScopeBar component was removed. See docs/development/conventions.md §1.'
        },
        {
          selector: 'Literal[value=/Function Lane/]',
          message:
            'Retired surface name (Phase 140): the second surface is the Workbench. See docs/development/conventions.md §1.'
        },
        {
          selector: 'TemplateElement[value.raw=/Function Lane/]',
          message:
            'Retired surface name (Phase 140): the second surface is the Workbench. See docs/development/conventions.md §1.'
        }
      ]
    }
  },
  {
    // This config necessarily contains the retired terms inside the
    // no-restricted-syntax selector patterns/messages; exempt it from its own
    // rule so it does not flag itself.
    files: ['eslint.config.js'],
    rules: { 'no-restricted-syntax': 'off' }
  },
  {
    files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
    languageOptions: {
      parserOptions: {
        projectService: true,
        extraFileExtensions: ['.svelte'],
        parser: ts.parser,
        svelteConfig
      }
    }
  },
  {
    ignores: [
      'build/',
      '.svelte-kit/',
      'dist/',
      'node_modules/',
      'playwright-report/',
      'test-results/',
      'coverage/',
      // Generated by `make codegen-ts`.
      'src/lib/api/types.ts'
    ]
  }
);
