-- AĒR ClickHouse Initialization Stub
--
-- Schema creation is now managed by the clickhouse-init container
-- using versioned SQL migrations in infra/clickhouse/migrations/.
-- See infra/clickhouse/migrate.sh for the migration runner.
--
-- This file is retained for backward compatibility with the Docker
-- entrypoint convention but is intentionally a no-op.