// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package handler

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for AvailableMetricEquivalenceLevel.
const (
	Absolute  AvailableMetricEquivalenceLevel = "absolute"
	Deviation AvailableMetricEquivalenceLevel = "deviation"
	Temporal  AvailableMetricEquivalenceLevel = "temporal"
)

// Valid indicates whether the value is a known member of the AvailableMetricEquivalenceLevel enum.
func (e AvailableMetricEquivalenceLevel) Valid() bool {
	switch e {
	case Absolute:
		return true
	case Deviation:
		return true
	case Temporal:
		return true
	default:
		return false
	}
}

// Defines values for AvailableMetricMinMeaningfulResolution.
const (
	AvailableMetricMinMeaningfulResolutionDaily   AvailableMetricMinMeaningfulResolution = "daily"
	AvailableMetricMinMeaningfulResolutionHourly  AvailableMetricMinMeaningfulResolution = "hourly"
	AvailableMetricMinMeaningfulResolutionMonthly AvailableMetricMinMeaningfulResolution = "monthly"
	AvailableMetricMinMeaningfulResolutionN5min   AvailableMetricMinMeaningfulResolution = "5min"
	AvailableMetricMinMeaningfulResolutionWeekly  AvailableMetricMinMeaningfulResolution = "weekly"
)

// Valid indicates whether the value is a known member of the AvailableMetricMinMeaningfulResolution enum.
func (e AvailableMetricMinMeaningfulResolution) Valid() bool {
	switch e {
	case AvailableMetricMinMeaningfulResolutionDaily:
		return true
	case AvailableMetricMinMeaningfulResolutionHourly:
		return true
	case AvailableMetricMinMeaningfulResolutionMonthly:
		return true
	case AvailableMetricMinMeaningfulResolutionN5min:
		return true
	case AvailableMetricMinMeaningfulResolutionWeekly:
		return true
	default:
		return false
	}
}

// Defines values for AvailableMetricValidationStatus.
const (
	AvailableMetricValidationStatusExpired     AvailableMetricValidationStatus = "expired"
	AvailableMetricValidationStatusUnvalidated AvailableMetricValidationStatus = "unvalidated"
	AvailableMetricValidationStatusValidated   AvailableMetricValidationStatus = "validated"
)

// Valid indicates whether the value is a known member of the AvailableMetricValidationStatus enum.
func (e AvailableMetricValidationStatus) Valid() bool {
	switch e {
	case AvailableMetricValidationStatusExpired:
		return true
	case AvailableMetricValidationStatusUnvalidated:
		return true
	case AvailableMetricValidationStatusValidated:
		return true
	default:
		return false
	}
}

// Defines values for ContentResponseEntityType.
const (
	ContentResponseEntityTypeDiscourseFunction ContentResponseEntityType = "discourse_function"
	ContentResponseEntityTypeMetric            ContentResponseEntityType = "metric"
	ContentResponseEntityTypeProbe             ContentResponseEntityType = "probe"
	ContentResponseEntityTypeRefusal           ContentResponseEntityType = "refusal"
)

// Valid indicates whether the value is a known member of the ContentResponseEntityType enum.
func (e ContentResponseEntityType) Valid() bool {
	switch e {
	case ContentResponseEntityTypeDiscourseFunction:
		return true
	case ContentResponseEntityTypeMetric:
		return true
	case ContentResponseEntityTypeProbe:
		return true
	case ContentResponseEntityTypeRefusal:
		return true
	default:
		return false
	}
}

// Defines values for ContentResponseLocale.
const (
	ContentResponseLocaleDe ContentResponseLocale = "de"
	ContentResponseLocaleEn ContentResponseLocale = "en"
)

// Valid indicates whether the value is a known member of the ContentResponseLocale enum.
func (e ContentResponseLocale) Valid() bool {
	switch e {
	case ContentResponseLocaleDe:
		return true
	case ContentResponseLocaleEn:
		return true
	default:
		return false
	}
}

// Defines values for MetricProvenanceTierClassification.
const (
	N1 MetricProvenanceTierClassification = 1
	N2 MetricProvenanceTierClassification = 2
	N3 MetricProvenanceTierClassification = 3
)

// Valid indicates whether the value is a known member of the MetricProvenanceTierClassification enum.
func (e MetricProvenanceTierClassification) Valid() bool {
	switch e {
	case N1:
		return true
	case N2:
		return true
	case N3:
		return true
	default:
		return false
	}
}

// Defines values for MetricProvenanceValidationStatus.
const (
	MetricProvenanceValidationStatusExpired     MetricProvenanceValidationStatus = "expired"
	MetricProvenanceValidationStatusUnvalidated MetricProvenanceValidationStatus = "unvalidated"
	MetricProvenanceValidationStatusValidated   MetricProvenanceValidationStatus = "validated"
)

// Valid indicates whether the value is a known member of the MetricProvenanceValidationStatus enum.
func (e MetricProvenanceValidationStatus) Valid() bool {
	switch e {
	case MetricProvenanceValidationStatusExpired:
		return true
	case MetricProvenanceValidationStatusUnvalidated:
		return true
	case MetricProvenanceValidationStatusValidated:
		return true
	default:
		return false
	}
}

// Defines values for GetContentParamsLocale.
const (
	GetContentParamsLocaleDe GetContentParamsLocale = "de"
	GetContentParamsLocaleEn GetContentParamsLocale = "en"
)

// Valid indicates whether the value is a known member of the GetContentParamsLocale enum.
func (e GetContentParamsLocale) Valid() bool {
	switch e {
	case GetContentParamsLocaleDe:
		return true
	case GetContentParamsLocaleEn:
		return true
	default:
		return false
	}
}

// Defines values for GetContentParamsEntityType.
const (
	GetContentParamsEntityTypeDiscourseFunction GetContentParamsEntityType = "discourse_function"
	GetContentParamsEntityTypeMetric            GetContentParamsEntityType = "metric"
	GetContentParamsEntityTypeProbe             GetContentParamsEntityType = "probe"
	GetContentParamsEntityTypeRefusal           GetContentParamsEntityType = "refusal"
)

// Valid indicates whether the value is a known member of the GetContentParamsEntityType enum.
func (e GetContentParamsEntityType) Valid() bool {
	switch e {
	case GetContentParamsEntityTypeDiscourseFunction:
		return true
	case GetContentParamsEntityTypeMetric:
		return true
	case GetContentParamsEntityTypeProbe:
		return true
	case GetContentParamsEntityTypeRefusal:
		return true
	default:
		return false
	}
}

// Defines values for GetMetricsParamsNormalization.
const (
	Raw    GetMetricsParamsNormalization = "raw"
	Zscore GetMetricsParamsNormalization = "zscore"
)

// Valid indicates whether the value is a known member of the GetMetricsParamsNormalization enum.
func (e GetMetricsParamsNormalization) Valid() bool {
	switch e {
	case Raw:
		return true
	case Zscore:
		return true
	default:
		return false
	}
}

// Defines values for GetMetricsParamsResolution.
const (
	GetMetricsParamsResolutionDaily   GetMetricsParamsResolution = "daily"
	GetMetricsParamsResolutionHourly  GetMetricsParamsResolution = "hourly"
	GetMetricsParamsResolutionMonthly GetMetricsParamsResolution = "monthly"
	GetMetricsParamsResolutionN5min   GetMetricsParamsResolution = "5min"
	GetMetricsParamsResolutionWeekly  GetMetricsParamsResolution = "weekly"
)

// Valid indicates whether the value is a known member of the GetMetricsParamsResolution enum.
func (e GetMetricsParamsResolution) Valid() bool {
	switch e {
	case GetMetricsParamsResolutionDaily:
		return true
	case GetMetricsParamsResolutionHourly:
		return true
	case GetMetricsParamsResolutionMonthly:
		return true
	case GetMetricsParamsResolutionN5min:
		return true
	case GetMetricsParamsResolutionWeekly:
		return true
	default:
		return false
	}
}

// AvailableMetric defines model for AvailableMetric.
type AvailableMetric struct {
	// EquivalenceLevel The highest equivalence level established for this metric. Null if no equivalence entry exists.
	EquivalenceLevel *AvailableMetricEquivalenceLevel `json:"equivalenceLevel,omitempty"`

	// EticConstruct The etic construct this metric maps to in the equivalence registry (e.g., "evaluative_polarity"). Null if no equivalence entry exists.
	EticConstruct *string `json:"eticConstruct,omitempty"`

	// MetricName The name of the metric.
	MetricName string `json:"metricName"`

	// MinMeaningfulResolution The finest temporal resolution at which this (metric, source) pair yields statistically meaningful aggregates. Derived from a static BFF config map seeded by Probe 0 publication rates. Null if no heuristic has been recorded for the metric-source pair.
	MinMeaningfulResolution *AvailableMetricMinMeaningfulResolution `json:"minMeaningfulResolution,omitempty"`

	// ValidationStatus Validation status derived from the metric_validity table. "unvalidated" if no entry exists, "validated" if a current entry exists with valid_until in the future, "expired" if the most recent entry has valid_until in the past.
	ValidationStatus AvailableMetricValidationStatus `json:"validationStatus"`
}

// AvailableMetricEquivalenceLevel The level of cross-cultural equivalence established for this metric. "temporal" means only temporal patterns are comparable, "deviation" means deviation from baseline is comparable, "absolute" means raw values are directly comparable across contexts.
type AvailableMetricEquivalenceLevel string

// AvailableMetricMinMeaningfulResolution Temporal aggregation resolution. "5min" is the finest grain stored in the gold layer; coarser values bucket via toStartOfHour/Day/Week/Month at query time.
type AvailableMetricMinMeaningfulResolution string

// AvailableMetricValidationStatus Validation status derived from the metric_validity table. "unvalidated" if no entry exists, "validated" if a current entry exists with valid_until in the future, "expired" if the most recent entry has valid_until in the past.
type AvailableMetricValidationStatus string

// ContentResponse Dual-Register content record for one entity. Sourced from versioned YAML files under configs/content/. Both registers are guaranteed present when the record is returned.
type ContentResponse struct {
	// ContentVersion Semver-style version string for the content record, e.g. "v2026-04-a". Incremented on every editorial update so consumers can detect staleness.
	ContentVersion string `json:"contentVersion"`

	// EntityId Canonical identifier of the entity.
	EntityId string `json:"entityId"`

	// EntityType Category of the entity.
	EntityType ContentResponseEntityType `json:"entityType"`

	// LastReviewedBy Name or role of the last reviewer.
	LastReviewedBy string `json:"lastReviewedBy"`

	// LastReviewedDate ISO 8601 date of last review.
	LastReviewedDate openapi_types.Date `json:"lastReviewedDate"`

	// Locale Language of the returned content.
	Locale ContentResponseLocale `json:"locale"`

	// Registers The paired semantic and methodological registers for one entity. Both registers are always present; the frontend decides which is prominent.
	Registers struct {
		// Methodological One register variant — either semantic or methodological.
		Methodological struct {
			// Long Full prose explanation (≤ 2000 characters). Rendered in Layer 4 (Provenance) panels where the user has descended to methodological detail.
			Long string `json:"long"`

			// Short Concise single-sentence summary (≤ 200 characters). Suitable for hover tooltips, badges, and compact surfaces.
			Short string `json:"short"`
		} `json:"methodological"`

		// Semantic One register variant — either semantic or methodological.
		Semantic struct {
			// Long Full prose explanation (≤ 2000 characters). Rendered in Layer 4 (Provenance) panels where the user has descended to methodological detail.
			Long string `json:"long"`

			// Short Concise single-sentence summary (≤ 200 characters). Suitable for hover tooltips, badges, and compact surfaces.
			Short string `json:"short"`
		} `json:"semantic"`
	} `json:"registers"`

	// WorkingPaperAnchors Optional list of Working Paper section references (e.g., "WP-002 §3") for downstream citation linking.
	WorkingPaperAnchors *[]string `json:"workingPaperAnchors,omitempty"`
}

// ContentResponseEntityType Category of the entity.
type ContentResponseEntityType string

// ContentResponseLocale Language of the returned content.
type ContentResponseLocale string

// MetricProvenance defines model for MetricProvenance.
type MetricProvenance struct {
	// AlgorithmDescription Plain-language description of the algorithm or lexicon that produces this metric.
	AlgorithmDescription string `json:"algorithmDescription"`

	// CulturalContextNotes Contextual notes on cross-cultural applicability, sourced from the metric_equivalence table when an entry exists. Null when no equivalence entry has been registered.
	CulturalContextNotes *string `json:"culturalContextNotes,omitempty"`

	// ExtractorVersionHash Short hash or version tag identifying the extractor implementation that produced the metric definition. Lets downstream consumers bind analytical results to a specific extractor revision.
	ExtractorVersionHash string `json:"extractorVersionHash"`

	// KnownLimitations Enumerated methodological limitations documented in the relevant Working Paper. May be empty for deterministic metrics with no known limitations.
	KnownLimitations []string `json:"knownLimitations"`

	// MetricName The canonical metric name.
	MetricName string `json:"metricName"`

	// TierClassification Methodological tier of the metric as defined in WP-002. Tier 1 = deterministic/lexical, Tier 2 = statistical/corpus-derived, Tier 3 = model-based/interpretive. The tier bounds the kind of claim the metric can support and is a primary signal for reflexive interpretation.
	TierClassification MetricProvenanceTierClassification `json:"tierClassification"`

	// ValidationStatus Validation status derived from the metric_validity table. "unvalidated" if no entry exists, "validated" if a current entry exists with valid_until in the future, "expired" if the most recent entry has valid_until in the past.
	ValidationStatus MetricProvenanceValidationStatus `json:"validationStatus"`
}

// MetricProvenanceTierClassification Methodological tier of the metric as defined in WP-002. Tier 1 = deterministic/lexical, Tier 2 = statistical/corpus-derived, Tier 3 = model-based/interpretive. The tier bounds the kind of claim the metric can support and is a primary signal for reflexive interpretation.
type MetricProvenanceTierClassification int

// MetricProvenanceValidationStatus Validation status derived from the metric_validity table. "unvalidated" if no entry exists, "validated" if a current entry exists with valid_until in the future, "expired" if the most recent entry has valid_until in the past.
type MetricProvenanceValidationStatus string

// Probe A probe is a bundle of one or more data sources that share a methodological identity (language, institutional role, classification tier). Probes are the unit of rendering on the Atmosphere surface.
// This schema intentionally carries no `reach` field. A probe's reach — where its content is consumed and discursively effective — cannot be measured from emission data alone and is not claimed by AĒR. Only the emission origin(s) are asserted here.
// Dual-Register content (emic designation, methodological register) is served separately via `/content/probe/{probeId}` and composed on the client. Keeping structural data and editorial content on different endpoints lets the content catalog evolve (versioning, locale switching) without perturbing the typed geometry feed.
type Probe struct {
	// EmissionPoints Geographic origins of the probe's bound publishers. Each point is rendered as a glowing marker on the globe. Multiple points allow federated broadcasters or multi-publisher probes to render correctly without implying a reach region between them.
	EmissionPoints []struct {
		// Label Human-readable label for this emission point (e.g., "Hamburg (Tagesschau / NDR)"). Rendered in hover tooltips and the L3 panel.
		Label string `json:"label"`

		// Latitude Geographic latitude of the emission origin (WGS84, degrees).
		Latitude float64 `json:"latitude"`

		// Longitude Geographic longitude of the emission origin (WGS84, degrees).
		Longitude float64 `json:"longitude"`
	} `json:"emissionPoints"`

	// Language Primary publication language as an ISO 639-1 code. Used by the client for content catalog locale fallback and for future language-scoped aggregations. Not a reach claim.
	Language string `json:"language"`

	// ProbeId Canonical identifier, matching the dossier directory under `docs/probes/` and the `probe` content-catalog key.
	ProbeId string `json:"probeId"`

	// Sources Canonical source names bound to this probe. Each entry corresponds to a row in the `sources` registry served by `/sources`. The client uses this to join per-source metrics back onto the probe marker (e.g., aggregating publication rates across `tagesschau` + `bundesregierung` into one pulse).
	Sources []string `json:"sources"`
}

// Source defines model for Source.
type Source struct {
	// DocumentationUrl Link to the probe dossier directory for this source (under docs/probes/<probe-id>/). The dossier groups WP-001 classification, WP-003 bias assessment, WP-005 temporal profile, and WP-006 observer-effect assessment for the probe to which this source belongs. Null when no dossier has been written.
	DocumentationUrl *string `json:"documentationUrl,omitempty"`

	// Name Canonical source identifier.
	Name string `json:"name"`

	// Type Source type discriminator (e.g., "rss", "scraper").
	Type string `json:"type"`

	// Url Origin URL (feed, API, or seed page).
	Url *string `json:"url,omitempty"`
}

// GetContentParams defines parameters for GetContent.
type GetContentParams struct {
	// Locale The language of the content to return. Defaults to "en".
	Locale *GetContentParamsLocale `form:"locale,omitempty" json:"locale,omitempty"`
}

// GetContentParamsLocale defines parameters for GetContent.
type GetContentParamsLocale string

// GetContentParamsEntityType defines parameters for GetContent.
type GetContentParamsEntityType string

// GetEntitiesParams defines parameters for GetEntities.
type GetEntitiesParams struct {
	// StartDate Start date for the metrics time range (ISO 8601)
	StartDate time.Time `form:"startDate" json:"startDate"`

	// EndDate End date for the metrics time range (ISO 8601)
	EndDate time.Time `form:"endDate" json:"endDate"`

	// Source Filter metrics by data source (e.g., "wikipedia")
	Source *string `form:"source,omitempty" json:"source,omitempty"`

	// Label Filter entities by NER label (e.g., "PER", "ORG", "LOC", "MISC")
	Label *string `form:"label,omitempty" json:"label,omitempty"`

	// Limit Maximum number of results to return (default 100, max 1000)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetLanguagesParams defines parameters for GetLanguages.
type GetLanguagesParams struct {
	// StartDate Start date for the metrics time range (ISO 8601)
	StartDate time.Time `form:"startDate" json:"startDate"`

	// EndDate End date for the metrics time range (ISO 8601)
	EndDate time.Time `form:"endDate" json:"endDate"`

	// Source Filter metrics by data source (e.g., "wikipedia")
	Source *string `form:"source,omitempty" json:"source,omitempty"`

	// Language Filter by ISO 639-1 language code (e.g., "de", "en").
	Language *string `form:"language,omitempty" json:"language,omitempty"`

	// Limit Maximum number of results to return (default 100, max 1000)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetMetricsParams defines parameters for GetMetrics.
type GetMetricsParams struct {
	// StartDate Start date for the metrics time range (ISO 8601)
	StartDate time.Time `form:"startDate" json:"startDate"`

	// EndDate End date for the metrics time range (ISO 8601)
	EndDate time.Time `form:"endDate" json:"endDate"`

	// Source Filter metrics by data source (e.g., "wikipedia")
	Source *string `form:"source,omitempty" json:"source,omitempty"`

	// MetricName Filter metrics by metric name (e.g., "word_count")
	MetricName *string `form:"metricName,omitempty" json:"metricName,omitempty"`

	// Normalization Normalization mode for metric values. "raw" returns values as stored. "zscore" returns z-score normalized values: (value - baseline_mean) / baseline_std. Requires baseline data and at least deviation-level equivalence validation.
	Normalization *GetMetricsParamsNormalization `form:"normalization,omitempty" json:"normalization,omitempty"`

	// Resolution Temporal aggregation resolution for the returned series. Maps to ClickHouse bucketing functions: 5min → toStartOfFiveMinute, hourly → toStartOfHour, daily → toStartOfDay, weekly → toStartOfWeek, monthly → toStartOfMonth. Wider buckets relax the per-request row cap proportionally.
	Resolution *GetMetricsParamsResolution `form:"resolution,omitempty" json:"resolution,omitempty"`
}

// GetMetricsParamsNormalization defines parameters for GetMetrics.
type GetMetricsParamsNormalization string

// GetMetricsParamsResolution defines parameters for GetMetrics.
type GetMetricsParamsResolution string

// GetMetricsAvailableParams defines parameters for GetMetricsAvailable.
type GetMetricsAvailableParams struct {
	// StartDate Start date for the metrics time range (ISO 8601)
	StartDate time.Time `form:"startDate" json:"startDate"`

	// EndDate End date for the metrics time range (ISO 8601)
	EndDate time.Time `form:"endDate" json:"endDate"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Dual-Register content for an entity
	// (GET /content/{entityType}/{entityId})
	GetContent(w http.ResponseWriter, r *http.Request, entityType GetContentParamsEntityType, entityId string, params GetContentParams)
	// Retrieve aggregated named entities
	// (GET /entities)
	GetEntities(w http.ResponseWriter, r *http.Request, params GetEntitiesParams)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Retrieve aggregated language detections
	// (GET /languages)
	GetLanguages(w http.ResponseWriter, r *http.Request, params GetLanguagesParams)
	// Retrieve aggregated time-series metrics
	// (GET /metrics)
	GetMetrics(w http.ResponseWriter, r *http.Request, params GetMetricsParams)
	// List available metric names
	// (GET /metrics/available)
	GetMetricsAvailable(w http.ResponseWriter, r *http.Request, params GetMetricsAvailableParams)
	// Retrieve provenance metadata for a metric
	// (GET /metrics/{metricName}/provenance)
	GetMetricProvenance(w http.ResponseWriter, r *http.Request, metricName string)
	// List active probes with emission geometry
	// (GET /probes)
	GetProbes(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// List known data sources with methodology documentation
	// (GET /sources)
	GetSources(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get Dual-Register content for an entity
// (GET /content/{entityType}/{entityId})
func (_ Unimplemented) GetContent(w http.ResponseWriter, r *http.Request, entityType GetContentParamsEntityType, entityId string, params GetContentParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve aggregated named entities
// (GET /entities)
func (_ Unimplemented) GetEntities(w http.ResponseWriter, r *http.Request, params GetEntitiesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve aggregated language detections
// (GET /languages)
func (_ Unimplemented) GetLanguages(w http.ResponseWriter, r *http.Request, params GetLanguagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve aggregated time-series metrics
// (GET /metrics)
func (_ Unimplemented) GetMetrics(w http.ResponseWriter, r *http.Request, params GetMetricsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List available metric names
// (GET /metrics/available)
func (_ Unimplemented) GetMetricsAvailable(w http.ResponseWriter, r *http.Request, params GetMetricsAvailableParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve provenance metadata for a metric
// (GET /metrics/{metricName}/provenance)
func (_ Unimplemented) GetMetricProvenance(w http.ResponseWriter, r *http.Request, metricName string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List active probes with emission geometry
// (GET /probes)
func (_ Unimplemented) GetProbes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness probe
// (GET /readyz)
func (_ Unimplemented) GetReadyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List known data sources with methodology documentation
// (GET /sources)
func (_ Unimplemented) GetSources(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetContent operation middleware
func (siw *ServerInterfaceWrapper) GetContent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "entityType" -------------
	var entityType GetContentParamsEntityType

	err = runtime.BindStyledParameterWithOptions("simple", "entityType", chi.URLParam(r, "entityType"), &entityType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entityType", Err: err})
		return
	}

	// ------------- Path parameter "entityId" -------------
	var entityId string

	err = runtime.BindStyledParameterWithOptions("simple", "entityId", chi.URLParam(r, "entityId"), &entityId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entityId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetContentParams

	// ------------- Optional query parameter "locale" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "locale", r.URL.Query(), &params.Locale, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locale", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetContent(w, r, entityType, entityId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEntities operation middleware
func (siw *ServerInterfaceWrapper) GetEntities(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEntitiesParams

	// ------------- Required query parameter "startDate" -------------

	if paramValue := r.URL.Query().Get("startDate"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "startDate"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "startDate", r.URL.Query(), &params.StartDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "startDate", Err: err})
		return
	}

	// ------------- Required query parameter "endDate" -------------

	if paramValue := r.URL.Query().Get("endDate"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "endDate"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "endDate", r.URL.Query(), &params.EndDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endDate", Err: err})
		return
	}

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source", r.URL.Query(), &params.Source, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	// ------------- Optional query parameter "label" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "label", r.URL.Query(), &params.Label, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "label", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEntities(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLanguages operation middleware
func (siw *ServerInterfaceWrapper) GetLanguages(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLanguagesParams

	// ------------- Required query parameter "startDate" -------------

	if paramValue := r.URL.Query().Get("startDate"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "startDate"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "startDate", r.URL.Query(), &params.StartDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "startDate", Err: err})
		return
	}

	// ------------- Required query parameter "endDate" -------------

	if paramValue := r.URL.Query().Get("endDate"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "endDate"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "endDate", r.URL.Query(), &params.EndDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endDate", Err: err})
		return
	}

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source", r.URL.Query(), &params.Source, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	// ------------- Optional query parameter "language" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "language", r.URL.Query(), &params.Language, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "language", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLanguages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetMetrics(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMetricsParams

	// ------------- Required query parameter "startDate" -------------

	if paramValue := r.URL.Query().Get("startDate"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "startDate"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "startDate", r.URL.Query(), &params.StartDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "startDate", Err: err})
		return
	}

	// ------------- Required query parameter "endDate" -------------

	if paramValue := r.URL.Query().Get("endDate"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "endDate"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "endDate", r.URL.Query(), &params.EndDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endDate", Err: err})
		return
	}

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source", r.URL.Query(), &params.Source, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	// ------------- Optional query parameter "metricName" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "metricName", r.URL.Query(), &params.MetricName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "metricName", Err: err})
		return
	}

	// ------------- Optional query parameter "normalization" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "normalization", r.URL.Query(), &params.Normalization, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "normalization", Err: err})
		return
	}

	// ------------- Optional query parameter "resolution" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "resolution", r.URL.Query(), &params.Resolution, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resolution", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetrics(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetricsAvailable operation middleware
func (siw *ServerInterfaceWrapper) GetMetricsAvailable(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMetricsAvailableParams

	// ------------- Required query parameter "startDate" -------------

	if paramValue := r.URL.Query().Get("startDate"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "startDate"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "startDate", r.URL.Query(), &params.StartDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "startDate", Err: err})
		return
	}

	// ------------- Required query parameter "endDate" -------------

	if paramValue := r.URL.Query().Get("endDate"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "endDate"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "endDate", r.URL.Query(), &params.EndDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endDate", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetricsAvailable(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetricProvenance operation middleware
func (siw *ServerInterfaceWrapper) GetMetricProvenance(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "metricName" -------------
	var metricName string

	err = runtime.BindStyledParameterWithOptions("simple", "metricName", chi.URLParam(r, "metricName"), &metricName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "metricName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetricProvenance(w, r, metricName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProbes operation middleware
func (siw *ServerInterfaceWrapper) GetProbes(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProbes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSources operation middleware
func (siw *ServerInterfaceWrapper) GetSources(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSources(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/content/{entityType}/{entityId}", wrapper.GetContent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/entities", wrapper.GetEntities)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/languages", wrapper.GetLanguages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/metrics", wrapper.GetMetrics)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/metrics/available", wrapper.GetMetricsAvailable)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/metrics/{metricName}/provenance", wrapper.GetMetricProvenance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/probes", wrapper.GetProbes)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadyz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sources", wrapper.GetSources)
	})

	return r
}

type GetContentRequestObject struct {
	EntityType GetContentParamsEntityType `json:"entityType"`
	EntityId   string                     `json:"entityId"`
	Params     GetContentParams
}

type GetContentResponseObject interface {
	VisitGetContentResponse(w http.ResponseWriter) error
}

type GetContent200JSONResponse ContentResponse

func (response GetContent200JSONResponse) VisitGetContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetContent400JSONResponse struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

func (response GetContent400JSONResponse) VisitGetContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetContent404JSONResponse struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

func (response GetContent404JSONResponse) VisitGetContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetContent500JSONResponse struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

func (response GetContent500JSONResponse) VisitGetContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetEntitiesRequestObject struct {
	Params GetEntitiesParams
}

type GetEntitiesResponseObject interface {
	VisitGetEntitiesResponse(w http.ResponseWriter) error
}

type GetEntities200JSONResponse []struct {
	// Count Number of occurrences within the queried time range.
	Count int64 `json:"count"`

	// EntityLabel The NER label (PER, ORG, LOC, MISC).
	EntityLabel string `json:"entityLabel"`

	// EntityText The extracted entity text (e.g., "Bundesregierung", "Berlin").
	EntityText string `json:"entityText"`

	// Sources Distinct data sources that produced this entity.
	Sources []string `json:"sources"`
}

func (response GetEntities200JSONResponse) VisitGetEntitiesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEntities400JSONResponse struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

func (response GetEntities400JSONResponse) VisitGetEntitiesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetEntities500JSONResponse struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

func (response GetEntities500JSONResponse) VisitGetEntitiesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse map[string]string

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLanguagesRequestObject struct {
	Params GetLanguagesParams
}

type GetLanguagesResponseObject interface {
	VisitGetLanguagesResponse(w http.ResponseWriter) error
}

type GetLanguages200JSONResponse []struct {
	// AvgConfidence Average confidence score for this language across matched documents.
	AvgConfidence float64 `json:"avgConfidence"`

	// Count Number of documents where this language was detected as the top candidate.
	Count int64 `json:"count"`

	// DetectedLanguage ISO 639-1 language code (e.g., "de", "en").
	DetectedLanguage string `json:"detectedLanguage"`

	// Sources Distinct data sources that produced this language detection.
	Sources []string `json:"sources"`
}

func (response GetLanguages200JSONResponse) VisitGetLanguagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLanguages400JSONResponse struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

func (response GetLanguages400JSONResponse) VisitGetLanguagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetLanguages500JSONResponse struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

func (response GetLanguages500JSONResponse) VisitGetLanguagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMetricsRequestObject struct {
	Params GetMetricsParams
}

type GetMetricsResponseObject interface {
	VisitGetMetricsResponse(w http.ResponseWriter) error
}

type GetMetrics200JSONResponse struct {
	// Data The aggregated time-series data points for the requested window.
	Data []struct {
		// MetricName The name of the metric (e.g., "word_count", "sentiment_score").
		MetricName string `json:"metricName"`

		// Source The data source that produced this metric (e.g., "tagesschau", "bundesregierung").
		Source string `json:"source"`

		// Timestamp The UTC timestamp of the aggregation interval.
		Timestamp time.Time `json:"timestamp"`

		// Value The aggregated sociological metric value.
		Value float64 `json:"value"`
	} `json:"data"`

	// ExcludedCount Number of source rows that were dropped from the aggregation because their article had no matching language detection. Always 0 for raw (non-normalized) queries; may be non-zero for `normalization=zscore`, where the language-scoped baseline join requires a detected language. A non-zero value surfaces data-quality gaps without altering the aggregated payload.
	ExcludedCount int64 `json:"excludedCount"`
}

func (response GetMetrics200JSONResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMetrics400JSONResponse struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

func (response GetMetrics400JSONResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetMetrics500JSONResponse struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

func (response GetMetrics500JSONResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMetricsAvailableRequestObject struct {
	Params GetMetricsAvailableParams
}

type GetMetricsAvailableResponseObject interface {
	VisitGetMetricsAvailableResponse(w http.ResponseWriter) error
}

type GetMetricsAvailable200JSONResponse []AvailableMetric

func (response GetMetricsAvailable200JSONResponse) VisitGetMetricsAvailableResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMetricsAvailable400JSONResponse struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

func (response GetMetricsAvailable400JSONResponse) VisitGetMetricsAvailableResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetMetricsAvailable500JSONResponse struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

func (response GetMetricsAvailable500JSONResponse) VisitGetMetricsAvailableResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMetricProvenanceRequestObject struct {
	MetricName string `json:"metricName"`
}

type GetMetricProvenanceResponseObject interface {
	VisitGetMetricProvenanceResponse(w http.ResponseWriter) error
}

type GetMetricProvenance200JSONResponse MetricProvenance

func (response GetMetricProvenance200JSONResponse) VisitGetMetricProvenanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMetricProvenance404JSONResponse struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

func (response GetMetricProvenance404JSONResponse) VisitGetMetricProvenanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetMetricProvenance500JSONResponse struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

func (response GetMetricProvenance500JSONResponse) VisitGetMetricProvenanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetProbesRequestObject struct {
}

type GetProbesResponseObject interface {
	VisitGetProbesResponse(w http.ResponseWriter) error
}

type GetProbes200JSONResponse []Probe

func (response GetProbes200JSONResponse) VisitGetProbesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProbes500JSONResponse struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

func (response GetProbes500JSONResponse) VisitGetProbesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse map[string]string

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReadyz503JSONResponse map[string]string

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetSourcesRequestObject struct {
}

type GetSourcesResponseObject interface {
	VisitGetSourcesResponse(w http.ResponseWriter) error
}

type GetSources200JSONResponse []Source

func (response GetSources200JSONResponse) VisitGetSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSources500JSONResponse struct {
	// Message A human-readable error message.
	Message string `json:"message"`
}

func (response GetSources500JSONResponse) VisitGetSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get Dual-Register content for an entity
	// (GET /content/{entityType}/{entityId})
	GetContent(ctx context.Context, request GetContentRequestObject) (GetContentResponseObject, error)
	// Retrieve aggregated named entities
	// (GET /entities)
	GetEntities(ctx context.Context, request GetEntitiesRequestObject) (GetEntitiesResponseObject, error)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// Retrieve aggregated language detections
	// (GET /languages)
	GetLanguages(ctx context.Context, request GetLanguagesRequestObject) (GetLanguagesResponseObject, error)
	// Retrieve aggregated time-series metrics
	// (GET /metrics)
	GetMetrics(ctx context.Context, request GetMetricsRequestObject) (GetMetricsResponseObject, error)
	// List available metric names
	// (GET /metrics/available)
	GetMetricsAvailable(ctx context.Context, request GetMetricsAvailableRequestObject) (GetMetricsAvailableResponseObject, error)
	// Retrieve provenance metadata for a metric
	// (GET /metrics/{metricName}/provenance)
	GetMetricProvenance(ctx context.Context, request GetMetricProvenanceRequestObject) (GetMetricProvenanceResponseObject, error)
	// List active probes with emission geometry
	// (GET /probes)
	GetProbes(ctx context.Context, request GetProbesRequestObject) (GetProbesResponseObject, error)
	// Readiness probe
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
	// List known data sources with methodology documentation
	// (GET /sources)
	GetSources(ctx context.Context, request GetSourcesRequestObject) (GetSourcesResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetContent operation middleware
func (sh *strictHandler) GetContent(w http.ResponseWriter, r *http.Request, entityType GetContentParamsEntityType, entityId string, params GetContentParams) {
	var request GetContentRequestObject

	request.EntityType = entityType
	request.EntityId = entityId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetContent(ctx, request.(GetContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetContent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetContentResponseObject); ok {
		if err := validResponse.VisitGetContentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEntities operation middleware
func (sh *strictHandler) GetEntities(w http.ResponseWriter, r *http.Request, params GetEntitiesParams) {
	var request GetEntitiesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEntities(ctx, request.(GetEntitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEntities")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEntitiesResponseObject); ok {
		if err := validResponse.VisitGetEntitiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLanguages operation middleware
func (sh *strictHandler) GetLanguages(w http.ResponseWriter, r *http.Request, params GetLanguagesParams) {
	var request GetLanguagesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLanguages(ctx, request.(GetLanguagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLanguages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLanguagesResponseObject); ok {
		if err := validResponse.VisitGetLanguagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMetrics operation middleware
func (sh *strictHandler) GetMetrics(w http.ResponseWriter, r *http.Request, params GetMetricsParams) {
	var request GetMetricsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetrics(ctx, request.(GetMetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetrics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMetricsResponseObject); ok {
		if err := validResponse.VisitGetMetricsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMetricsAvailable operation middleware
func (sh *strictHandler) GetMetricsAvailable(w http.ResponseWriter, r *http.Request, params GetMetricsAvailableParams) {
	var request GetMetricsAvailableRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetricsAvailable(ctx, request.(GetMetricsAvailableRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetricsAvailable")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMetricsAvailableResponseObject); ok {
		if err := validResponse.VisitGetMetricsAvailableResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMetricProvenance operation middleware
func (sh *strictHandler) GetMetricProvenance(w http.ResponseWriter, r *http.Request, metricName string) {
	var request GetMetricProvenanceRequestObject

	request.MetricName = metricName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetricProvenance(ctx, request.(GetMetricProvenanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetricProvenance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMetricProvenanceResponseObject); ok {
		if err := validResponse.VisitGetMetricProvenanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProbes operation middleware
func (sh *strictHandler) GetProbes(w http.ResponseWriter, r *http.Request) {
	var request GetProbesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProbes(ctx, request.(GetProbesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProbes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProbesResponseObject); ok {
		if err := validResponse.VisitGetProbesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSources operation middleware
func (sh *strictHandler) GetSources(w http.ResponseWriter, r *http.Request) {
	var request GetSourcesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSources(ctx, request.(GetSourcesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSources")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSourcesResponseObject); ok {
		if err := validResponse.VisitGetSourcesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
