#!/usr/bin/env python3
"""Generate the per-language `metric_validity` scaffold from the manifest.

ADR-024 / Phase 118a deliverable. Reads
`services/analysis-worker/configs/language_capabilities.yaml` and emits
`infra/clickhouse/seed/metric_validity_scaffold_generated.sql` — one block
per `(language, metric_name, tier)` triple drawn from `sentiment_tier1`,
`sentiment_tier2_default`, `sentiment_tier2_refinement`, plus the NER
`entity_count` baseline for any language with an `ner` capability.

The hand-maintained `metric_validity_scaffold.sql` is preserved for cross-
context entries (e.g. `entity_link_confidence`); the generated file covers
per-language entries. Both seed files are loaded at ClickHouse init in
lexicographic order.

Manual edits to the generated file are forbidden — `make scaffold-metric-
validity && git diff --exit-code` is the drift gate.

Why not actual INSERTs?
  The `aer_gold.metric_validity` schema (migration 000006) does not carry a
  `validation_status` column — the BFF derives that string from `valid_until`
  (no row → "unvalidated", row+future → "validated", row+past → "expired").
  The canonical encoding for an unvalidated metric is therefore the *absence*
  of a row. This file documents the (metric, language, tier) triples the
  manifest declares so a future annotation-study reviewer has a complete
  punch-list, while staying a no-op SELECT against the live schema.
"""

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass
from pathlib import Path

# Ensure the worker's `internal` package is importable when this script is
# run from the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT / "services" / "analysis-worker"))

from internal.models.language_capability import (  # noqa: E402
    CapabilityManifest,
    load_manifest,
)


_DEFAULT_OUTPUT = (
    _REPO_ROOT / "infra" / "clickhouse" / "seed" / "metric_validity_scaffold_generated.sql"
)
_HEADER = """\
-- AUTO-GENERATED. DO NOT EDIT.
--
-- Generated by scripts/generate_metric_validity_scaffold.py from
-- services/analysis-worker/configs/language_capabilities.yaml
-- (Phase 118a / ADR-024). Re-run via `make scaffold-metric-validity`.
--
-- Companion to infra/clickhouse/seed/metric_validity_scaffold.sql:
--   * the hand-maintained file holds cross-context entries
--     (`context_key='*:*:*'`, e.g. entity_link_confidence);
--   * this file holds per-language entries derived from the manifest.
--
-- Both seed files are loaded at ClickHouse init in lexicographic order.
--
-- Why no INSERTs? The `aer_gold.metric_validity` table (migration 000006)
-- does not carry a `validation_status` column. The BFF derives validation
-- status from `valid_until` (no row → "unvalidated", row+future →
-- "validated", row+past → "expired"). The canonical encoding for an
-- unvalidated metric is therefore the absence of a row. This file
-- documents the (metric, language, tier) triples the manifest declares
-- so a future annotation-study reviewer has a complete punch-list, while
-- staying a no-op SELECT against the live schema.
--
-- error_taxonomy default for every entry below:
--   {"reason":"engineering default; awaiting WP-002 annotation study"}
--
"""

_FOOTER = (
    "SELECT 'metric_validity_scaffold_generated: no-op — see file header for rationale' AS note;\n"
)


@dataclass(frozen=True, order=True)
class ScaffoldEntry:
    language: str
    metric_name: str
    tier: float
    method: str


def collect_entries(manifest: CapabilityManifest) -> list[ScaffoldEntry]:
    """Walk every (language, metric_name) the manifest declares.

    Per ADR-024: `sentiment_tier1`, `sentiment_tier2_default`,
    `sentiment_tier2_refinement`, plus the NER `entity_count` baseline for
    any language with an `ner` block.
    """
    entries: list[ScaffoldEntry] = []
    for lang_code in sorted(manifest.languages):
        lang = manifest.languages[lang_code]

        if lang.ner is not None:
            # Tier-1 baseline: `entity_count` is the per-document NER metric;
            # the spans themselves are uncountable in `metric_validity`'s
            # numeric model, so this is the only NER row.
            entries.append(
                ScaffoldEntry(
                    language=lang_code,
                    metric_name="entity_count",
                    tier=1.0,
                    method="spacy_ner",
                )
            )

        if lang.sentiment_tier1 is not None:
            entries.append(
                ScaffoldEntry(
                    language=lang_code,
                    metric_name=lang.sentiment_tier1.metric_name,
                    tier=lang.sentiment_tier1.tier,
                    method=lang.sentiment_tier1.method,
                )
            )
        if lang.sentiment_tier2_default is not None:
            entries.append(
                ScaffoldEntry(
                    language=lang_code,
                    metric_name=lang.sentiment_tier2_default.metric_name,
                    tier=lang.sentiment_tier2_default.tier,
                    method=lang.sentiment_tier2_default.method,
                )
            )
        if lang.sentiment_tier2_refinement is not None:
            entries.append(
                ScaffoldEntry(
                    language=lang_code,
                    metric_name=lang.sentiment_tier2_refinement.metric_name,
                    tier=lang.sentiment_tier2_refinement.tier,
                    method=lang.sentiment_tier2_refinement.method,
                )
            )
    return sorted(entries)


def render_sql(entries: list[ScaffoldEntry]) -> str:
    """Render the SQL file. Output is stable across runs."""
    parts: list[str] = [_HEADER]
    if not entries:
        parts.append("-- (no per-language entries in the current manifest)\n\n")
    for entry in entries:
        parts.append(
            "-- ---------------------------------------------------------------------------\n"
            f"-- {entry.metric_name} — language={entry.language}, tier={entry.tier}\n"
            "-- ---------------------------------------------------------------------------\n"
            f"--   metric_name : {entry.metric_name}\n"
            f"--   context_key : {entry.language}:*:*\n"
            f"--   tier        : {entry.tier}\n"
            f"--   method      : {entry.method}\n"
            "--   error_taxonomy:\n"
            "--     {\"reason\":\"engineering default; awaiting WP-002 annotation study\"}\n"
            "\n"
        )
    parts.append(_FOOTER)
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="Path to language_capabilities.yaml (defaults to the bundled manifest).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=_DEFAULT_OUTPUT,
        help="Path to the generated SQL file.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Exit non-zero if the on-disk file would change. "
            "Used by the CI drift gate."
        ),
    )
    args = parser.parse_args()

    manifest = load_manifest(args.manifest)
    entries = collect_entries(manifest)
    rendered = render_sql(entries)

    if args.check:
        existing = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if existing != rendered:
            print(
                f"DRIFT: {args.output} is out of sync with the manifest. "
                f"Run `make scaffold-metric-validity` and commit the diff.",
                file=sys.stderr,
            )
            return 1
        print(f"{args.output} is up to date.")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    rel = os.path.relpath(args.output, _REPO_ROOT)
    print(f"Wrote {rel} ({len(entries)} entries).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
