#!/usr/bin/env bash
# gen_runtime_env.sh — generate the secret-free runtime env file (Phase 155 / D9).
#
# Reads .env and writes .env.runtime containing every NON-secret variable (drops
# the secrets named in infra/secrets/secrets.manifest plus deploy-meta vars).
# compose.yaml mounts it via `env_file:` on the application services, so a new
# NON-secret config var is forwarded to the services by construction — no need to
# remember to add a `- VAR=${VAR}` line (the durable fix behind the SEC-032/036/
# 040/043/046 "var not forwarded" class).
#
# Secrets NEVER go here: env_file values land in Docker's on-disk container
# config (config.v2.json), so secrets stay on the Docker-secrets / tmpfs path.
# This script asserts that invariant before writing.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT/.env}"
OUT="${RUNTIME_ENV_FILE:-$ROOT/.env.runtime}"
MANIFEST="$ROOT/infra/secrets/secrets.manifest"

if [ ! -f "$ENV_FILE" ]; then
  echo "gen_runtime_env: $ENV_FILE not found" >&2
  exit 1
fi

# Exclusion set: every secret name (so no secret is ever forwarded as an env var)
# plus deploy-meta that is not service config.
declare -A EXCLUDE=()
if [ -f "$MANIFEST" ]; then
  while IFS= read -r _raw; do
    _n=${_raw%%#*}
    _n=$(printf '%s' "$_n" | tr -d '[:space:]')
    [ -n "$_n" ] && EXCLUDE["$_n"]=1
  done <"$MANIFEST"
fi
for _n in COMPOSE_FILE IMAGE_TAG GHCR_OWNER AER_SECRETS_DIR; do EXCLUDE["$_n"]=1; done

umask 077
: >"$OUT"
{
  echo "# GENERATED by scripts/operations/gen_runtime_env.sh (Phase 155 / D9) — do not edit."
  echo "# Non-secret runtime config forwarded to the app services via compose env_file."
} >>"$OUT"

while IFS= read -r _line || [ -n "$_line" ]; do
  case "$_line" in '' | \#*) continue ;; esac
  case "$_line" in *=*) ;; *) continue ;; esac
  _key=${_line%%=*}
  case "$_key" in [A-Za-z_]*) ;; *) continue ;; esac
  [ -n "${EXCLUDE[$_key]:-}" ] && continue
  printf '%s\n' "$_line" >>"$OUT"
done <"$ENV_FILE"

# Safety net: refuse to emit a file that contains a secret name as a key.
for _n in "${!EXCLUDE[@]}"; do
  if grep -qE "^${_n}=" "$OUT"; then
    echo "gen_runtime_env: FATAL — secret '$_n' leaked into $OUT; refusing" >&2
    rm -f "$OUT"
    exit 1
  fi
done

echo "gen_runtime_env: wrote $(grep -cE '^[A-Za-z_]' "$OUT") non-secret var(s) to $OUT"
