/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve aggregated time-series metrics
         * @description Fetches gold-layer metrics for the dashboard's "weather map" visualization.
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available metric names
         * @description Returns the distinct metric names present in the gold layer for the given time range. Enables frontends to discover metrics dynamically.
         */
        get: operations["getMetricsAvailable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/{metricName}/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve provenance metadata for a metric
         * @description Returns the methodological provenance for a single metric: tier classification, algorithm description, known limitations, current validation status, extractor version hash, and cultural-context notes. Static fields are sourced from the BFF's `metric_provenance.yaml` config; dynamic fields (`validationStatus`, `culturalContextNotes`) are resolved against the `metric_validity` and `metric_equivalence` tables.
         */
        get: operations["getMetricProvenance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve aggregated named entities
         * @description Fetches named entities (persons, organizations, locations) extracted from processed documents, aggregated by entity text and label.
         */
        get: operations["getEntities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve aggregated language detections
         * @description Fetches detected languages aggregated across processed documents. Only rank-1 (top candidate) detections are included in the aggregation.
         */
        get: operations["getLanguages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List known data sources with methodology documentation
         * @description Returns the canonical list of data sources configured in AĒR together with optional links to their methodological documentation (e.g., bias profiles under `docs/methodology/`). The list is served from a static BFF config mirroring the PostgreSQL `sources` table so the BFF does not require a direct Postgres connection.
         */
        get: operations["getSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 if the service process is alive. Used by Kubernetes liveness probes.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 if all dependencies (ClickHouse) are reachable. Used by Kubernetes readiness probes.
         */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/{entityType}/{entityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dual-Register content for an entity
         * @description Returns the semantic and methodological register text for a single entity (metric, probe, discourse function, or refusal type). Content is sourced from versioned YAML files under `services/bff-api/configs/content/` and loaded at startup. The `locale` query parameter selects the language; defaults to `en`. Returns 404 if no content entry exists for the requested entity and locale combination.
         */
        get: operations["getContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Validation status derived from the metric_validity table. "unvalidated" if no entry exists, "validated" if a current entry exists with valid_until in the future, "expired" if the most recent entry has valid_until in the past.
         * @example unvalidated
         * @enum {string}
         */
        ValidationStatus: "unvalidated" | "validated" | "expired";
        /**
         * @description Temporal aggregation resolution. "5min" is the finest grain stored in the gold layer; coarser values bucket via toStartOfHour/Day/Week/Month at query time.
         * @example hourly
         * @enum {string}
         */
        Resolution: "5min" | "hourly" | "daily" | "weekly" | "monthly";
        /**
         * @description The level of cross-cultural equivalence established for this metric. "temporal" means only temporal patterns are comparable, "deviation" means deviation from baseline is comparable, "absolute" means raw values are directly comparable across contexts.
         * @example deviation
         * @enum {string}
         */
        EquivalenceLevel: "temporal" | "deviation" | "absolute";
        AvailableMetric: {
            /**
             * @description The name of the metric.
             * @example word_count
             */
            metricName: string;
            validationStatus: components["schemas"]["ValidationStatus"];
            /**
             * @description The etic construct this metric maps to in the equivalence registry (e.g., "evaluative_polarity"). Null if no equivalence entry exists.
             * @example null
             */
            eticConstruct?: string | null;
            /** @description The highest equivalence level established for this metric. Null if no equivalence entry exists. */
            equivalenceLevel?: components["schemas"]["EquivalenceLevel"] | null;
            /** @description The finest temporal resolution at which this (metric, source) pair yields statistically meaningful aggregates. Derived from a static BFF config map seeded by Probe 0 publication rates. Null if no heuristic has been recorded for the metric-source pair. */
            minMeaningfulResolution?: components["schemas"]["Resolution"] | null;
        };
        /**
         * @description Methodological tier of the metric as defined in WP-002. Tier 1 = deterministic/lexical, Tier 2 = statistical/corpus-derived, Tier 3 = model-based/interpretive. The tier bounds the kind of claim the metric can support and is a primary signal for reflexive interpretation.
         * @example 1
         * @enum {integer}
         */
        TierClassification: 1 | 2 | 3;
        MetricProvenance: {
            /**
             * @description The canonical metric name.
             * @example sentiment_score
             */
            metricName: string;
            tierClassification: components["schemas"]["TierClassification"];
            /** @description Plain-language description of the algorithm or lexicon that produces this metric. */
            algorithmDescription: string;
            /** @description Enumerated methodological limitations documented in the relevant Working Paper. May be empty for deterministic metrics with no known limitations. */
            knownLimitations: string[];
            validationStatus: components["schemas"]["ValidationStatus"];
            /**
             * @description Short hash or version tag identifying the extractor implementation that produced the metric definition. Lets downstream consumers bind analytical results to a specific extractor revision.
             * @example v1
             */
            extractorVersionHash: string;
            /** @description Contextual notes on cross-cultural applicability, sourced from the metric_equivalence table when an entry exists. Null when no equivalence entry has been registered. */
            culturalContextNotes?: string | null;
        };
        Source: {
            /**
             * @description Canonical source identifier.
             * @example tagesschau
             */
            name: string;
            /**
             * @description Source type discriminator (e.g., "rss", "scraper").
             * @example rss
             */
            type: string;
            /** @description Origin URL (feed, API, or seed page). */
            url?: string | null;
            /**
             * @description Link to the probe dossier directory for this source (under docs/probes/<probe-id>/). The dossier groups WP-001 classification, WP-003 bias assessment, WP-005 temporal profile, and WP-006 observer-effect assessment for the probe to which this source belongs. Null when no dossier has been written.
             * @example docs/probes/probe-0-de-institutional-rss/
             */
            documentationUrl?: string | null;
        };
        /** @description One register variant — either semantic or methodological. */
        ContentRegister: {
            /** @description Concise single-sentence summary (≤ 200 characters). Suitable for hover tooltips, badges, and compact surfaces. */
            short: string;
            /** @description Full prose explanation (≤ 2000 characters). Rendered in Layer 4 (Provenance) panels where the user has descended to methodological detail. */
            long: string;
        };
        /** @description The paired semantic and methodological registers for one entity. Both registers are always present; the frontend decides which is prominent. */
        ContentRegisters: {
            semantic: components["schemas"]["ContentRegister"];
            methodological: components["schemas"]["ContentRegister"];
        };
        /** @description Dual-Register content record for one entity. Sourced from versioned YAML files under configs/content/. Both registers are guaranteed present when the record is returned. */
        ContentResponse: {
            /**
             * @description Canonical identifier of the entity.
             * @example sentiment_score
             */
            entityId: string;
            /**
             * @description Category of the entity.
             * @example metric
             * @enum {string}
             */
            entityType: "metric" | "probe" | "discourse_function" | "refusal";
            /**
             * @description Language of the returned content.
             * @example en
             * @enum {string}
             */
            locale: "en" | "de";
            registers: components["schemas"]["ContentRegisters"];
            /**
             * @description Semver-style version string for the content record, e.g. "v2026-04-a". Incremented on every editorial update so consumers can detect staleness.
             * @example v2026-04-a
             */
            contentVersion: string;
            /**
             * @description Name or role of the last reviewer.
             * @example Engineering Team
             */
            lastReviewedBy: string;
            /**
             * Format: date
             * @description ISO 8601 date of last review.
             * @example 2026-04-19
             */
            lastReviewedDate: string;
            /**
             * @description Optional list of Working Paper section references (e.g., "WP-002 §3") for downstream citation linking.
             * @example [
             *       "WP-002 §3"
             *     ]
             */
            workingPaperAnchors?: string[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMetrics: {
        parameters: {
            query: {
                /** @description Start date for the metrics time range (ISO 8601) */
                startDate: string;
                /** @description End date for the metrics time range (ISO 8601) */
                endDate: string;
                /** @description Filter metrics by data source (e.g., "wikipedia") */
                source?: string;
                /** @description Filter metrics by metric name (e.g., "word_count") */
                metricName?: string;
                /** @description Normalization mode for metric values. "raw" returns values as stored. "zscore" returns z-score normalized values: (value - baseline_mean) / baseline_std. Requires baseline data and at least deviation-level equivalence validation. */
                normalization?: "raw" | "zscore";
                /** @description Temporal aggregation resolution for the returned series. Maps to ClickHouse bucketing functions: 5min → toStartOfFiveMinute, hourly → toStartOfHour, daily → toStartOfDay, weekly → toStartOfWeek, monthly → toStartOfMonth. Wider buckets relax the per-request row cap proportionally. */
                resolution?: "5min" | "hourly" | "daily" | "weekly" | "monthly";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Envelope containing the time-series data points and query metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description The aggregated time-series data points for the requested window. */
                        data: {
                            /**
                             * Format: date-time
                             * @description The UTC timestamp of the aggregation interval.
                             */
                            timestamp: string;
                            /**
                             * Format: double
                             * @description The aggregated sociological metric value.
                             */
                            value: number;
                            /** @description The data source that produced this metric (e.g., "tagesschau", "bundesregierung"). */
                            source: string;
                            /** @description The name of the metric (e.g., "word_count", "sentiment_score"). */
                            metricName: string;
                        }[];
                        /**
                         * Format: int64
                         * @description Number of source rows that were dropped from the aggregation because their article had no matching language detection. Always 0 for raw (non-normalized) queries; may be non-zero for `normalization=zscore`, where the language-scoped baseline join requires a detected language. A non-zero value surfaces data-quality gaps without altering the aggregated payload.
                         */
                        excludedCount: number;
                    };
                };
            };
            /** @description Missing required parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description A human-readable error message. */
                        message: string;
                    };
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description A human-readable error message. */
                        message: string;
                    };
                };
            };
        };
    };
    getMetricsAvailable: {
        parameters: {
            query: {
                /** @description Start date for the metrics time range (ISO 8601) */
                startDate: string;
                /** @description End date for the metrics time range (ISO 8601) */
                endDate: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of available metrics with validation status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableMetric"][];
                };
            };
            /** @description Missing required parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description A human-readable error message. */
                        message: string;
                    };
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description A human-readable error message. */
                        message: string;
                    };
                };
            };
        };
    };
    getMetricProvenance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The canonical metric name (e.g., "word_count"). */
                metricName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The provenance metadata for the requested metric. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricProvenance"];
                };
            };
            /** @description No provenance entry exists for the requested metric. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description A human-readable error message. */
                        message: string;
                    };
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description A human-readable error message. */
                        message: string;
                    };
                };
            };
        };
    };
    getEntities: {
        parameters: {
            query: {
                /** @description Start date for the metrics time range (ISO 8601) */
                startDate: string;
                /** @description End date for the metrics time range (ISO 8601) */
                endDate: string;
                /** @description Filter metrics by data source (e.g., "wikipedia") */
                source?: string;
                /** @description Filter entities by NER label (e.g., "PER", "ORG", "LOC", "MISC") */
                label?: string;
                /** @description Maximum number of results to return (default 100, max 1000) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of aggregated entity results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description The extracted entity text (e.g., "Bundesregierung", "Berlin"). */
                        entityText: string;
                        /** @description The NER label (PER, ORG, LOC, MISC). */
                        entityLabel: string;
                        /**
                         * Format: int64
                         * @description Number of occurrences within the queried time range.
                         */
                        count: number;
                        /** @description Distinct data sources that produced this entity. */
                        sources: string[];
                    }[];
                };
            };
            /** @description Missing required parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description A human-readable error message. */
                        message: string;
                    };
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description A human-readable error message. */
                        message: string;
                    };
                };
            };
        };
    };
    getLanguages: {
        parameters: {
            query: {
                /** @description Start date for the metrics time range (ISO 8601) */
                startDate: string;
                /** @description End date for the metrics time range (ISO 8601) */
                endDate: string;
                /** @description Filter metrics by data source (e.g., "wikipedia") */
                source?: string;
                /** @description Filter by ISO 639-1 language code (e.g., "de", "en"). */
                language?: string;
                /** @description Maximum number of results to return (default 100, max 1000) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of aggregated language detection results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description ISO 639-1 language code (e.g., "de", "en"). */
                        detectedLanguage: string;
                        /**
                         * Format: int64
                         * @description Number of documents where this language was detected as the top candidate.
                         */
                        count: number;
                        /**
                         * Format: double
                         * @description Average confidence score for this language across matched documents.
                         */
                        avgConfidence: number;
                        /** @description Distinct data sources that produced this language detection. */
                        sources: string[];
                    }[];
                };
            };
            /** @description Missing required parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description A human-readable error message. */
                        message: string;
                    };
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description A human-readable error message. */
                        message: string;
                    };
                };
            };
        };
    };
    getSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list of known sources. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"][];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description A human-readable error message. */
                        message: string;
                    };
                };
            };
        };
    };
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready to serve traffic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Service is not ready — one or more dependencies are unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getContent: {
        parameters: {
            query?: {
                /** @description The language of the content to return. Defaults to "en". */
                locale?: "en" | "de";
            };
            header?: never;
            path: {
                /** @description The category of the entity. */
                entityType: "metric" | "probe" | "discourse_function" | "refusal";
                /** @description The canonical identifier of the entity (e.g., "sentiment_score"). */
                entityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Content found for the requested entity and locale. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentResponse"];
                };
            };
            /** @description Invalid entityType value. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description A human-readable error message. */
                        message: string;
                    };
                };
            };
            /** @description No content found for the requested entity or locale. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description A human-readable error message. */
                        message: string;
                    };
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description A human-readable error message. */
                        message: string;
                    };
                };
            };
        };
    };
}
